import { AccessibilityRequirement } from "./standards-types";

export const STANDARDS_DATA: AccessibilityRequirement[] = [
  // ===== A: דרך נגישה ותנועה כללית =====
  {
    id: "req-a-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.1",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רציפות דרך נגישה",
    requirementTitle: "רציפות הדרך הנגישה",
    practicalRequirement: "הדרך הנגישה תהיה רציפה מכניסת המגרש ועד כניסת הבניין, ללא מכשולים, הפרשי גובה או חסימות.",
    defectText: "הדרך הנגישה אינה רציפה / חסומה / אינה מאפשרת מעבר בטוח לאדם עם מוגבלות.",
    correctionText: "יש לפנות את המכשול / להשלים את הדרך הנגישה / לתקן את ההפרש כך שהדרך תהיה רציפה ובטוחה.",
    severity: "critical",
    measurementFields: ["אורך החסימה (מ')", "מיקום החסימה"],
    inspectionMethod: "בדיקה חזותית ומדידה לאורך מסלול הגישה מהכניסה למגרש עד הכניסה לבניין.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "רציפות", "מכשול", "גישה"],
  },
  {
    id: "req-a-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.2",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רוחב דרך נגישה",
    requirementTitle: "רוחב מינימלי של דרך נגישה",
    practicalRequirement: "רוחב הדרך הנגישה יהיה לפחות 1.80 מ' לתנועה דו-כיוונית של כיסאות גלגלים, ולפחות 1.30 מ' לתנועה חד-כיוונית.",
    defectText: "רוחב הדרך הנגישה נמוך מהנדרש.",
    correctionText: "יש להרחיב את הדרך הנגישה לרוחב מינימלי הנדרש (1.80 מ' לדו-כיוונית / 1.30 מ' לחד-כיוונית).",
    severity: "critical",
    measurementFields: ["רוחב מדוד (מ')", "מיקום הצרות", "כיוון תנועה"],
    inspectionMethod: "מדידה בסרט מדידה בנקודות הצרות לאורך הדרך.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["דרך נגישה", "רוחב", "מינימום"],
  },
  {
    id: "req-a-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.3",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "שיפוע דרך נגישה",
    requirementTitle: "שיפוע רוחבי של דרך נגישה",
    practicalRequirement: "השיפוע הרוחבי של הדרך הנגישה לא יעלה על 2%.",
    defectText: "השיפוע הרוחבי של הדרך הנגישה עולה על 2%.",
    correctionText: "יש לתקן את פני המשטח כך שהשיפוע הרוחבי לא יעלה על 2%.",
    severity: "medium",
    measurementFields: ["שיפוע מדוד (%)"],
    inspectionMethod: "מדידת שיפוע באמצעות מד שיפוע (קלינומטר) בנקודות שונות.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "שיפוע", "רוחבי"],
  },
  {
    id: "req-a-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.4",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "גמר משטח",
    requirementTitle: "מרקם ויציבות משטח הדרך הנגישה",
    practicalRequirement: "משטח הדרך הנגישה יהיה יציב, חזק ולא החלקי. אין להשתמש בחצץ רופף או אבנים בלתי יציבות.",
    defectText: "משטח הדרך הנגישה אינו יציב / החלקי / לא אחיד.",
    correctionText: "יש להחליף או לתקן את מרקם המשטח לחומר יציב, חזק ולא החלקי.",
    severity: "medium",
    measurementFields: ["תיאור החומר"],
    inspectionMethod: "בדיקה חזותית ומישוש לאורך הדרך הנגישה.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "משטח", "החלקה", "יציבות"],
  },
  {
    id: "req-a-005",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.1",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רמפות וכבשים",
    requirementTitle: "שיפוע מרבי של רמפה בחוץ",
    practicalRequirement: "שיפוע הרמפה בשטח חוץ לא יעלה על 8% (1:12.5). בשטחים פתוחים מיוחדים ניתן עד 10%.",
    defectText: "שיפוע הרמפה תלול יותר מ-8% המותר לרמפות בחוץ.",
    correctionText: "יש להקטין את שיפוע הרמפה ל-8% לכל היותר על ידי הארכת הרמפה.",
    severity: "critical",
    measurementFields: ["שיפוע מדוד (%)", "אורך הרמפה (מ')", "גובה ההפרש (מ')"],
    inspectionMethod: "מדידת שיפוע הרמפה בקלינומטר ומדידת אורך וגובה.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["רמפה", "שיפוע", "כבש", "חוץ"],
  },
  {
    id: "req-a-006",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.2",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רמפות וכבשים",
    requirementTitle: "רוחב מינימלי של רמפה",
    practicalRequirement: "רוחב הרמפה יהיה לפחות 1.30 מ' בין מעקות/אבני שפה.",
    defectText: "רוחב הרמפה נמוך מ-1.30 מ'.",
    correctionText: "יש להרחיב את הרמפה לרוחב מינימלי של 1.30 מ' בין המעקות.",
    severity: "critical",
    measurementFields: ["רוחב הרמפה (מ')"],
    inspectionMethod: "מדידת רוחב הרמפה בין שני המעקות/אבני השפה.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "רוחב", "מינימום"],
  },
  {
    id: "req-a-007",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.3",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רמפות וכבשים",
    requirementTitle: "פודסט (משטח מנוחה) ברמפה",
    practicalRequirement: "בכל שינוי גובה של 0.75 מ' ברמפה יהיה פודסט מנוחה. ממדי הפודסט לפחות 1.30×1.30 מ' (או 1.80×1.80 מ' בצמתים).",
    defectText: "חסר פודסט מנוחה בעת שינוי גובה מעל 0.75 מ' / פודסט קטן מהנדרש.",
    correctionText: "יש להוסיף פודסט בגודל 1.30×1.30 מ' לפחות בכל שינוי גובה של 0.75 מ'.",
    severity: "medium",
    measurementFields: ["ממדי הפודסט (מ')", "גובה בין פודסטים (מ')"],
    inspectionMethod: "מדידת ממדי הפודסט ובדיקת מרחק גובה בין הפודסטים.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "פודסט", "מנוחה"],
  },
  {
    id: "req-a-008",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.4",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רמפות וכבשים",
    requirementTitle: "הגנת קצה ברמפה",
    practicalRequirement: "לאורך קצות הרמפה שאינם גובלים בקיר יהיה אמצעי הגנה: אבן שפה בגובה לפחות 9 ס\"מ, עם פתח מקסימלי 5 ס\"מ בין האבן למשטח.",
    defectText: "חסרה אבן שפה / גובה אבן שפה קטן מ-9 ס\"מ / פתח בין האבן למשטח גדול מ-5 ס\"מ.",
    correctionText: "יש להתקין אבן שפה בגובה לפחות 9 ס\"מ לאורך קצות הרמפה הפתוחים.",
    severity: "medium",
    measurementFields: ["גובה אבן שפה (ס\"מ)", "פתח בין אבן לרצפה (ס\"מ)"],
    inspectionMethod: "מדידת גובה אבן השפה ובדיקת הפתח בין האבן למשטח.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "הגנת קצה", "אבן שפה"],
  },
  {
    id: "req-a-009",
    standardPart: 'ת"י 1918 חלק 1',
    clause: "4.2",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "גובה פנוי",
    requirementTitle: "גובה פנוי מינימלי מעל הדרך הנגישה",
    practicalRequirement: "הגובה הפנוי לאורך כל הדרך הנגישה יהיה לפחות 2.00 מ'.",
    defectText: "הגובה הפנוי מעל הדרך הנגישה נמוך מ-2.00 מ'.",
    correctionText: "יש להסיר את המכשול/הבליטה שמפחיתה את הגובה הפנוי או לסמן אזהרה ולהסיט את המסלול.",
    severity: "critical",
    measurementFields: ["גובה פנוי מדוד (מ')"],
    inspectionMethod: "מדידת גובה פנוי בנקודות הנמוכות ביותר.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["גובה פנוי", "דרך נגישה"],
  },

  // ===== B: חניות נגישות =====
  {
    id: "req-b-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.1",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "מספר מקומות חניה נגישים",
    requirementTitle: "מספר מינימלי של מקומות חניה נגישים",
    practicalRequirement: "יש לסמן מספר מינימלי של מקומות חניה נגישים בהתאם לגודל החניון, לפחות מקום אחד.",
    defectText: "אין מספיק מקומות חניה נגישים מסומנים / אין כלל מקומות חניה נגישים.",
    correctionText: "יש לסמן ולהקצות מקומות חניה נגישים בהתאם לדרישות התקן.",
    severity: "critical",
    measurementFields: ["מספר מקומות חניה כולל", "מספר מקומות נגישים קיימים", "מספר מקומות נגישים נדרשים"],
    inspectionMethod: "ספירת מקומות חניה נגישים וסה\"כ מקומות בחניון.",
    appliesTo: ["parking"],
    tags: ["חניה", "נגיש", "מספר"],
  },
  {
    id: "req-b-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.2",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "ממדי מקום חניה נגיש",
    requirementTitle: "ממדי מקום חניה נגיש",
    practicalRequirement: "מקום חניה נגיש יהיה ברוחב 3.30 מ' לפחות (כולל פס גישה של 1.20 מ') ובאורך 5.00 מ' לפחות.",
    defectText: "מקום החניה הנגיש צר מדי / קצר מדי ואינו עומד בממדים הנדרשים.",
    correctionText: "יש לשנות את תיחום מקום החניה הנגיש לממדים הנדרשים: רוחב 3.30 מ' ואורך 5.00 מ' לפחות.",
    severity: "critical",
    measurementFields: ["רוחב מקום חניה (מ')", "אורך מקום חניה (מ')", "רוחב פס גישה (מ')"],
    inspectionMethod: "מדידת ממדי מקום החניה הנגיש ורוחב פס הגישה.",
    appliesTo: ["parking"],
    tags: ["חניה", "ממדים", "רוחב"],
  },
  {
    id: "req-b-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.3",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "סימון חניה נגישה",
    requirementTitle: "סימון וסמלי חניה נגישה",
    practicalRequirement: "מקום החניה הנגיש יסומן בסמל הנכות הבינלאומי על גבי הכביש ובשילוט אנכי.",
    defectText: "חסר סימון על הכביש / שילוט אנכי של חניה נגישה / הסימון דהוי ואינו קריא.",
    correctionText: "יש לסמן מחדש את מקום החניה הנגיש בסמל הנכות הבינלאומי ולהציב שילוט אנכי.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית של הסימון הרצפי והשילוט האנכי.",
    appliesTo: ["parking", "signage"],
    tags: ["חניה", "סימון", "שילוט", "סמל נכות"],
  },
  {
    id: "req-b-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.4",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "מיקום חניה נגישה",
    requirementTitle: "קרבת חניה נגישה לכניסה נגישה",
    practicalRequirement: "מקום החניה הנגיש יהיה קרוב ככל האפשר לכניסה הנגישה, ויחובר אליה בדרך נגישה רציפה.",
    defectText: "מקום החניה הנגיש אינו קרוב לכניסה הנגישה / אין דרך נגישה רציפה בין החניה לכניסה.",
    correctionText: "יש להקצות מקום חניה נגיש בסמוך לכניסה הנגישה ולהבטיח דרך נגישה רציפה ביניהם.",
    severity: "medium",
    measurementFields: ["מרחק מהכניסה (מ')"],
    inspectionMethod: "מדידת מרחק ובדיקת נגישות המסלול בין החניה לכניסה.",
    appliesTo: ["parking", "accessible-route"],
    tags: ["חניה", "מיקום", "כניסה נגישה"],
  },

  // ===== C: כניסה לבניין =====
  {
    id: "req-c-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.1",
    category: "C. כניסה לבניין",
    categoryCode: "C",
    subCategory: "כניסה נגישה",
    requirementTitle: "כניסה נגישה לבניין",
    practicalRequirement: "לבניין תהיה לפחות כניסה נגישה אחת. הכניסה הנגישה תהיה זהה לכניסה הראשית לבניין או סמוכה לה.",
    defectText: "אין כניסה נגישה / הכניסה הנגישה רחוקה מהכניסה הראשית ואינה מסומנת.",
    correctionText: "יש לייצר כניסה נגישה הזהה לכניסה הראשית או לסמן בצורה ברורה את הכניסה הנגישה הקרובה.",
    severity: "critical",
    measurementFields: ["מרחק מכניסה ראשית (מ')"],
    inspectionMethod: "בדיקת קיום כניסה נגישה ומיקומה ביחס לכניסה הראשית.",
    appliesTo: ["exterior"],
    tags: ["כניסה", "נגישה", "בניין"],
  },
  {
    id: "req-c-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.2",
    category: "C. כניסה לבניין",
    categoryCode: "C",
    subCategory: "רוחב פתח כניסה",
    requirementTitle: "רוחב מינימלי של פתח הכניסה הנגישה",
    practicalRequirement: "רוחב פתח הכניסה הנגישה (בין מסגרות הדלת) יהיה לפחות 1.10 מ'. לדלתות סיבוביות/מסתובבות – יש כניסה נגישה חלופית.",
    defectText: "רוחב פתח הכניסה הנגישה נמוך מ-1.10 מ'.",
    correctionText: "יש להרחיב את פתח הכניסה הנגישה לרוחב מינימלי של 1.10 מ'.",
    severity: "critical",
    measurementFields: ["רוחב פתח (מ')"],
    inspectionMethod: "מדידת רוחב פתח הדלת הנגישה בין מסגרות הדלת.",
    appliesTo: ["exterior"],
    tags: ["כניסה", "רוחב", "פתח", "דלת"],
  },
  {
    id: "req-c-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.3",
    category: "C. כניסה לבניין",
    categoryCode: "C",
    subCategory: "כיסוי כניסה",
    requirementTitle: "כיסוי/מחסה מעל הכניסה הנגישה",
    practicalRequirement: "מעל הכניסה הנגישה יהיה כיסוי (סככה/קנופה) בממדים של 1.30×1.70 מ' לפחות, או 1.50×1.50 מ'.",
    defectText: "חסר כיסוי/סככה מעל הכניסה הנגישה / הכיסוי קטן מהנדרש.",
    correctionText: "יש להתקין כיסוי מעל הכניסה הנגישה בממדים של לפחות 1.30×1.70 מ'.",
    severity: "low",
    measurementFields: ["ממדי הכיסוי (מ')"],
    inspectionMethod: "מדידת ממדי הכיסוי מעל הכניסה הנגישה.",
    appliesTo: ["exterior"],
    tags: ["כניסה", "כיסוי", "סככה", "מחסה"],
  },
  {
    id: "req-c-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.4",
    category: "C. כניסה לבניין",
    categoryCode: "C",
    subCategory: "אינטרקום/פעמון",
    requirementTitle: "מערכת אינטרקום נגישה בכניסה",
    practicalRequirement: "כאשר השער/הדלת אינם ניתנים לפתיחה עצמאית מבחוץ, תהיה מערכת אינטרקום נגישה בגובה 85-110 ס\"מ.",
    defectText: "אין מערכת אינטרקום / האינטרקום ממוקם בגובה בלתי נגיש / אינו פועל.",
    correctionText: "יש להתקין אינטרקום נגיש בגובה 85-110 ס\"מ מהרצפה.",
    severity: "critical",
    measurementFields: ["גובה האינטרקום (ס\"מ)"],
    inspectionMethod: "מדידת גובה האינטרקום ובדיקת תקינות פעולתו.",
    appliesTo: ["exterior"],
    tags: ["כניסה", "אינטרקום", "פעמון", "פתיחה"],
  },
  {
    id: "req-c-005",
    standardPart: 'ת"י 1918 חלק 5.1',
    clause: "2.1",
    category: "C. כניסה לבניין",
    categoryCode: "C",
    subCategory: "תאורת כניסה",
    requirementTitle: "תאורה נאותה בכניסה לבניין",
    practicalRequirement: "תאורת הכניסה לבניין תהיה בעוצמה של 100-200 לוקס, ללא סנוור.",
    defectText: "תאורת הכניסה אינה מספקת / חורגת מ-200 לוקס ויוצרת סנוור.",
    correctionText: "יש להתאים את תאורת הכניסה לעוצמה של 100-200 לוקס ללא סנוור.",
    severity: "low",
    measurementFields: ["עוצמת תאורה (לוקס)"],
    inspectionMethod: "מדידת עוצמת התאורה בכניסה באמצעות מד לוקס.",
    appliesTo: ["exterior"],
    tags: ["כניסה", "תאורה", "לוקס"],
  },

  // ===== D: פנים הבניין – מעברים ומסדרונות =====
  {
    id: "req-d-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "5.1",
    category: "D. פנים הבניין – מעברים ומסדרונות",
    categoryCode: "D",
    subCategory: "רוחב מסדרון",
    requirementTitle: "רוחב מינימלי של מסדרון/מעבר",
    practicalRequirement: "רוחב המסדרון יהיה לפחות 1.30 מ'. ניתן להצר ל-0.90 מ' לקטעים קצרים, בתנאי שיהיו שטחי תמרון כל 15 מ'.",
    defectText: "רוחב המסדרון / המעבר נמוך מ-1.30 מ'.",
    correctionText: "יש להרחיב את המסדרון לרוחב מינימלי של 1.30 מ' או לסדר שטחי תמרון לאורכו.",
    severity: "critical",
    measurementFields: ["רוחב מדוד (מ')", "מיקום הצרות"],
    inspectionMethod: "מדידת רוחב המסדרון בנקודות הצרות.",
    appliesTo: ["interior", "accessible-route"],
    tags: ["מסדרון", "רוחב", "מעבר"],
  },
  {
    id: "req-d-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "5.2",
    category: "D. פנים הבניין – מעברים ומסדרונות",
    categoryCode: "D",
    subCategory: "שטח תמרון",
    requirementTitle: "שטח תמרון לכיסא גלגלים",
    practicalRequirement: "שטח התמרון יאפשר סיבוב של כיסא גלגלים בטווח עד 1.50 מ' בקוטר עד לגובה 0.68 מ'.",
    defectText: "חסר שטח תמרון (לפחות 1.50 מ' × 1.50 מ') בקצות המסדרון / ליד הדלתות.",
    correctionText: "יש לפנות שטח תמרון בקוטר 1.50 מ' לפחות בנקודות הנדרשות.",
    severity: "medium",
    measurementFields: ["ממדי שטח התמרון (מ')"],
    inspectionMethod: "מדידת שטח התמרון בנקודות הנדרשות.",
    appliesTo: ["interior", "accessible-route"],
    tags: ["תמרון", "כיסא גלגלים", "סיבוב"],
  },
  {
    id: "req-d-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "5.3",
    category: "D. פנים הבניין – מעברים ומסדרונות",
    categoryCode: "D",
    subCategory: "שיפוע רמפה פנימית",
    requirementTitle: "שיפוע מרבי של רמפה פנימית",
    practicalRequirement: "שיפוע רמפה פנימית לא יעלה על 8%. רמפה בשיפוע מעל 6% מחייבת מדרגות מקבילות.",
    defectText: "שיפוע הרמפה הפנימית עולה על 8% המותר.",
    correctionText: "יש להקטין את שיפוע הרמפה הפנימית ל-8% לכל היותר.",
    severity: "critical",
    measurementFields: ["שיפוע מדוד (%)"],
    inspectionMethod: "מדידת שיפוע הרמפה בקלינומטר.",
    appliesTo: ["interior", "accessible-route"],
    tags: ["רמפה", "שיפוע", "פנים"],
  },

  // ===== E: דלתות ופתחים =====
  {
    id: "req-e-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "6.1",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "רוחב פתח דלת",
    requirementTitle: "רוחב פנוי מינימלי של דלת",
    practicalRequirement: "רוחב הפתח הפנוי של הדלת (אחרי פתיחה ל-90 מעלות) יהיה לפחות 0.80 מ'. בשטחי ספורט / ייעוד מיוחד – לפחות 1.10 מ'.",
    defectText: "רוחב הפתח הפנוי של הדלת קטן מ-0.80 מ'.",
    correctionText: "יש להרחיב את פתח הדלת לרוחב פנוי של לפחות 0.80 מ'.",
    severity: "critical",
    measurementFields: ["רוחב פנוי מדוד (מ')"],
    inspectionMethod: "מדידת הרוחב הפנוי של הדלת בעת פתיחה מלאה ל-90 מעלות.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "רוחב", "פתח"],
  },
  {
    id: "req-e-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "6.2",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "כוח פתיחת דלת",
    requirementTitle: "כוח פתיחה מרבי של דלת",
    practicalRequirement: "כוח הדרוש לפתיחת הדלת: דלת פנימית – לא יעלה על 22 ניוטון; דלת חיצונית – לא יעלה על 30 ניוטון.",
    defectText: "כוח הפתיחה של הדלת עולה על הערך המותר (22 ניוטון פנימית / 30 ניוטון חיצונית).",
    correctionText: "יש לכוון את קפיץ הדלת / מגיף הדלת לכוח פתיחה שאינו עולה על המותר.",
    severity: "medium",
    measurementFields: ["כוח פתיחה מדוד (ניוטון)", "סוג הדלת (פנימית/חיצונית)"],
    inspectionMethod: "מדידת כוח פתיחת הדלת בדינמומטר.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "כוח פתיחה", "קפיץ"],
  },
  {
    id: "req-e-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "6.3",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "עיכוב סגירת דלת",
    requirementTitle: "עיכוב מינימלי בסגירת דלת אוטומטית",
    practicalRequirement: "דלת עם מגיף אוטומטי לא תיסגר בפחות מ-5 שניות מרגע הפתיחה המלאה.",
    defectText: "הדלת האוטומטית נסגרת בפחות מ-5 שניות.",
    correctionText: "יש לכוון את מגיף הדלת כך שהדלת לא תיסגר לפני שעברו 5 שניות.",
    severity: "medium",
    measurementFields: ["זמן סגירה (שניות)"],
    inspectionMethod: "מדידת זמן סגירת הדלת בשעון עצור.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "סגירה", "מגיף", "עיכוב"],
  },
  {
    id: "req-e-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "6.4",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "סף דלת",
    requirementTitle: "גובה סף דלת מרבי",
    practicalRequirement: "גובה סף הדלת לא יעלה על 2 ס\"מ בכניסה לבניין / חיבור לחוץ; לא יעלה על 1.5 ס\"מ בדלתות פנימיות.",
    defectText: "גובה סף הדלת עולה על המותר (2 ס\"מ בכניסה / 1.5 ס\"מ בפנים).",
    correctionText: "יש להנמיך את סף הדלת לגובה שאינו עולה על הנדרש, או להסירו ולהתקין פרופיל שטוח.",
    severity: "medium",
    measurementFields: ["גובה הסף (ס\"מ)", "מיקום הדלת (כניסה/פנימית)"],
    inspectionMethod: "מדידת גובה סף הדלת.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "סף", "גובה"],
  },
  {
    id: "req-e-005",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "6.5",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "ידית דלת",
    requirementTitle: "ידית דלת נגישה",
    practicalRequirement: "ידית הדלת תהיה בגובה 85-110 ס\"מ. ידיות עגולות (כדוריות) אסורות; מומלצת ידית ממונפת (לבר).",
    defectText: "ידית הדלת ממוקמת מחוץ לטווח 85-110 ס\"מ / ידית עגולה/כדורית שאינה ניתנת לאחיזה.",
    correctionText: "יש להחליף את ידית הדלת לידית ממונפת ולהתקינה בגובה 85-110 ס\"מ.",
    severity: "medium",
    measurementFields: ["גובה ידית (ס\"מ)", "סוג הידית"],
    inspectionMethod: "מדידת גובה הידית ובדיקת סוגה.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "ידית", "ידית ממונפת"],
  },

  // ===== F: מדרגות ומעקות =====
  {
    id: "req-f-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "8.1",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "ממדי שלב מדרגה",
    requirementTitle: "גובה ועומק שלב מדרגה",
    practicalRequirement: "גובה שלב יהיה בין 10 ס\"מ ל-15 ס\"מ (בחוץ) או עד 18 ס\"מ (בפנים). עומק שלב לפחות 31 ס\"מ (בחוץ) / 28 ס\"מ (בפנים). כל השלבים אחידים.",
    defectText: "גובה השלב חורג מהטווח המותר / שלבים אינם אחידים / עומק שלב קטן מהנדרש.",
    correctionText: "יש לתקן את ממדי השלבים לעמוד בדרישות התקן.",
    severity: "medium",
    measurementFields: ["גובה שלב (ס\"מ)", "עומק שלב (ס\"מ)", "מספר שלבים לא אחידים"],
    inspectionMethod: "מדידת גובה ועומק מספר שלבים לאורך גרם המדרגות.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "שלב", "גובה", "עומק"],
  },
  {
    id: "req-f-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.2",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "פס אזהרה במדרגות",
    requirementTitle: "פס אזהרה בראש ובתחתית מדרגות",
    practicalRequirement: "בראש ובתחתית כל גרם מדרגות יהיה רצועת אזהרה מישושית ברוחב לפחות 60 ס\"מ לאורך כל רוחב המדרגות, בניגוד חזותי ומישושי.",
    defectText: "חסרה רצועת אזהרה מישושית בראש/תחתית המדרגות / רוחב הרצועה קטן מ-60 ס\"מ.",
    correctionText: "יש להתקין רצועת אזהרה מישושית ברוחב 60 ס\"מ לפחות בראש ובתחתית המדרגות.",
    severity: "critical",
    measurementFields: ["רוחב רצועת האזהרה (ס\"מ)", "קיום ניגוד חזותי (כן/לא)"],
    inspectionMethod: "בדיקת קיום, רוחב ואיכות רצועת האזהרה בראש ובתחתית המדרגות.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "אזהרה", "מישושי", "עיוורים"],
  },
  {
    id: "req-f-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "8.3",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "סימון קצה שלב",
    requirementTitle: "סימון ניגוד בקצה שלב המדרגה",
    practicalRequirement: "קצה כל שלב מדרגה יסומן ברצועה בניגוד חזותי, ברוחב עד 3 ס\"מ ממרחק הקצה, לפחות 80% מרוחב השלב.",
    defectText: "חסר סימון ניגוד בקצה שלב המדרגה / הסימון קטן מ-80% מרוחב השלב.",
    correctionText: "יש להוסיף רצועה בניגוד חזותי בקצה שלב המדרגה לאורך לפחות 80% מרוחב השלב.",
    severity: "medium",
    measurementFields: ["אחוז כיסוי (%)"],
    inspectionMethod: "בדיקה חזותית של קצות השלבים.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "ניגוד", "קצה שלב", "בטיחות"],
  },
  {
    id: "req-f-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.1",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "מאחזי יד",
    requirementTitle: "גובה מאחז יד",
    practicalRequirement: "מאחז היד יהיה בגובה 90-95 ס\"מ מעל אף השלב. ניתן להוסיף מאחז נמוך ב-70-75 ס\"מ.",
    defectText: "גובה מאחז היד חורג מהטווח 90-95 ס\"מ.",
    correctionText: "יש לכוון את מאחז היד לגובה הנדרש של 90-95 ס\"מ.",
    severity: "medium",
    measurementFields: ["גובה מאחז (ס\"מ)"],
    inspectionMethod: "מדידת גובה מאחז היד מאף השלב.",
    appliesTo: ["interior", "exterior", "accessible-route"],
    tags: ["מאחז יד", "גובה", "מדרגות"],
  },
  {
    id: "req-f-005",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.2",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "מאחזי יד",
    requirementTitle: "מאחזי יד משני הצדדים ומאריך קצה",
    practicalRequirement: "מאחזי יד יהיו משני הצדדים. המאחז יארך 30 ס\"מ מעבר לשלב הראשון ולשלב האחרון של גרם המדרגות.",
    defectText: "מאחז יד חסר בצד אחד / אינו נמשך 30 ס\"מ מעבר לשלב הראשון/אחרון.",
    correctionText: "יש להתקין מאחז יד משני הצדדים ולהאריכו 30 ס\"מ מעבר לשלבים הראשון והאחרון.",
    severity: "medium",
    measurementFields: ["קיום בשני הצדדים (כן/לא)", "אורך הארכה (ס\"מ)"],
    inspectionMethod: "בדיקת קיום מאחז יד בשני הצדדים ומדידת הארכת הקצה.",
    appliesTo: ["interior", "exterior", "accessible-route"],
    tags: ["מאחז יד", "הארכה", "שני הצדדים"],
  },
  {
    id: "req-f-006",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.3",
    category: "F. מדרגות ומעקות",
    categoryCode: "F",
    subCategory: "מאחזי יד",
    requirementTitle: "צורה וממדי מאחז יד",
    practicalRequirement: "מאחז יד עגול: קוטר 3-4 ס\"מ. מאחז לא עגול: רוחב 3-6 ס\"מ עם פינות מעוגלות. גוף אחיזה: 4 ס\"מ פנוי מכל כיוון.",
    defectText: "ממדי מאחז היד אינם בטווח הנדרש / אין מרווח אחיזה מספק (4 ס\"מ).",
    correctionText: "יש להחליף את מאחז היד לקוטר/ממד הנכון ולהבטיח מרווח אחיזה של 4 ס\"מ.",
    severity: "medium",
    measurementFields: ["קוטר/רוחב מאחז (ס\"מ)", "מרווח אחיזה (ס\"מ)"],
    inspectionMethod: "מדידת קוטר/רוחב מאחז היד ומרווח האחיזה.",
    appliesTo: ["interior", "exterior", "accessible-route"],
    tags: ["מאחז יד", "ממדים", "קוטר"],
  },

  // ===== G: מעליות ומעלונים =====
  {
    id: "req-g-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.1",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "דלת מעלית",
    requirementTitle: "רוחב דלת מעלית נגישה",
    practicalRequirement: "רוחב פתח הדלת של המעלית הנגישה יהיה לפחות 0.90 מ'.",
    defectText: "רוחב פתח דלת המעלית קטן מ-0.90 מ'.",
    correctionText: "יש להחליף את דלת המעלית לדלת רחבה יותר – לפחות 0.90 מ'.",
    severity: "critical",
    measurementFields: ["רוחב פתח דלת (מ')"],
    inspectionMethod: "מדידת רוחב פתח דלת המעלית.",
    appliesTo: ["interior"],
    tags: ["מעלית", "דלת", "רוחב"],
  },
  {
    id: "req-g-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.2",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "תא מעלית",
    requirementTitle: "ממדי תא מעלית נגישה",
    practicalRequirement: "ממדי תא המעלית הנגישה (מעלית סוג 3): לפחות 1.10 מ' × 1.40 מ'. המעלית תכיל כיסא גלגלים עם מטפל.",
    defectText: "ממדי תא המעלית קטנים מהנדרש (1.10×1.40 מ').",
    correctionText: "יש להחליף את המעלית למעלית בממדים נגישים של לפחות 1.10×1.40 מ'.",
    severity: "critical",
    measurementFields: ["עומק תא (מ')", "רוחב תא (מ')"],
    inspectionMethod: "מדידת ממדי תא המעלית פנימה.",
    appliesTo: ["interior"],
    tags: ["מעלית", "תא", "ממדים"],
  },
  {
    id: "req-g-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.3",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "לחצנים ובקרה",
    requirementTitle: "גובה לחצנים בתא מעלית",
    practicalRequirement: "לחצני הקומות בתוך תא המעלית יהיו בגובה 85-120 ס\"מ מהרצפה.",
    defectText: "לחצני הקומות ממוקמים מחוץ לטווח 85-120 ס\"מ.",
    correctionText: "יש להוסיף לחצנים בגובה 85-120 ס\"מ בנוסף לאלה הקיימים, או להחליף את לוח הבקרה.",
    severity: "medium",
    measurementFields: ["גובה לחצנים (ס\"מ)"],
    inspectionMethod: "מדידת גובה הלחצנים הנמוכים והגבוהים בלוח הבקרה של המעלית.",
    appliesTo: ["interior"],
    tags: ["מעלית", "לחצנים", "בקרה", "גובה"],
  },
  {
    id: "req-g-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.4",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "שילוט מעלית",
    requirementTitle: "שלט מישושי של מספר קומה על מסגרת המעלית",
    practicalRequirement: "על מסגרת דלת המעלית בכל קומה, משני הצדדים, יהיה שלט מישושי עם מספר הקומה בניגוד חזותי ובכתב ברייל.",
    defectText: "חסר שלט מישושי / כתב ברייל על מסגרת דלת המעלית / שלט ממוקם בצד אחד בלבד.",
    correctionText: "יש להתקין שלט מישושי עם מספר הקומה וכתב ברייל על מסגרת הדלת משני הצדדים.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום שלט מישושי משני צידי דלת המעלית בכל קומה.",
    appliesTo: ["interior", "signage"],
    tags: ["מעלית", "שילוט", "ברייל", "מישושי"],
  },

  // ===== H: שירותי נגישות =====
  {
    id: "req-h-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.1",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "ממדי תא שירותים נגיש",
    requirementTitle: "ממדי תא שירותים נגיש",
    practicalRequirement: "תא שירותים נגיש סוג 1 (פינתי): לפחות 1.50×2.00 מ'. סוג 2 (מרכזי): לפחות 2.40×2.20 מ'.",
    defectText: "ממדי תא השירותים הנגיש קטנים מהנדרש.",
    correctionText: "יש להגדיל את תא השירותים הנגיש לממדים הנדרשים.",
    severity: "critical",
    measurementFields: ["רוחב תא (מ')", "עומק תא (מ')", "סוג תא (1/2)"],
    inspectionMethod: "מדידת ממדי תא השירותים הנגיש.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "תא", "ממדים", "נגיש"],
  },
  {
    id: "req-h-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.2",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "אסלה",
    requirementTitle: "גובה אסלה וסוגה",
    practicalRequirement: "גובה מושב האסלה יהיה 45-50 ס\"מ מהרצפה. האסלה תהיה בעלת מושב סגור, קשיח, עמיד לקורוזיה.",
    defectText: "גובה מושב האסלה חורג מהטווח 45-50 ס\"מ / מושב פתוח / מושב אינו קשיח.",
    correctionText: "יש לכוון את גובה האסלה ל-45-50 ס\"מ ולהחליף את המושב לסגור וקשיח.",
    severity: "medium",
    measurementFields: ["גובה מושב (ס\"מ)"],
    inspectionMethod: "מדידת גובה מושב האסלה מהרצפה ובדיקת סוג המושב.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "אסלה", "גובה", "מושב"],
  },
  {
    id: "req-h-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.3",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מוט אחיזה מתקפל",
    requirementTitle: "מוט אחיזה מתקפל ליד האסלה",
    practicalRequirement: "מוט אחיזה מתקפל: אורך 73-90 ס\"מ; קצהו מגיע עד חזית האסלה; משקל פתיחה לא יעלה על 30 ניוטון; עומד בעומס של 590 ניוטון אופקי ו-981 ניוטון אנכי.",
    defectText: "מוט האחיזה קצר מדי / לא מגיע לחזית האסלה / כוח פתיחה עולה על 30 ניוטון / אינו יציב.",
    correctionText: "יש להחליף/לכוון את מוט האחיזה לאורך הנדרש ולבדוק יציבותו.",
    severity: "critical",
    measurementFields: ["אורך מוט (ס\"מ)", "כוח פתיחה (ניוטון)"],
    inspectionMethod: "מדידת אורך המוט, בדיקת הגעתו לחזית האסלה ומדידת כוח הפתיחה.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מוט אחיזה", "מתקפל"],
  },
  {
    id: "req-h-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.4",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מוט אחיזה קבוע",
    requirementTitle: "מוט אחיזה קבוע ליד האסלה",
    practicalRequirement: "מוט אחיזה קבוע בצורת L: כל זרוע לפחות 60 ס\"מ. גובה הזרוע האופקית: 75-85 ס\"מ. מרחק ממרכז האסלה: 38±2 ס\"מ.",
    defectText: "מוט האחיזה הקבוע קצר / אינו בגובה הנכון / מרחק מהאסלה שגוי.",
    correctionText: "יש להתקין מוט L קבוע בגובה 75-85 ס\"מ ובמרחק 38±2 ס\"מ ממרכז האסלה.",
    severity: "critical",
    measurementFields: ["גובה זרוע אופקית (ס\"מ)", "מרחק ממרכז אסלה (ס\"מ)", "אורך זרועות (ס\"מ)"],
    inspectionMethod: "מדידת גובה ומיקום מוט האחיזה הקבוע.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מוט אחיזה", "קבוע", "L"],
  },
  {
    id: "req-h-005",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.5",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מרחק פנוי ליד האסלה",
    requirementTitle: "מרחק פנוי לצד האסלה",
    practicalRequirement: "בסוג 1 (פינתי): מרחק פנוי של לפחות 80 ס\"מ לצד האסלה. בסוג 2 (מרכזי): לפחות 100 ס\"מ בצד הכיור.",
    defectText: "המרחק הפנוי לצד האסלה קטן מהנדרש.",
    correctionText: "יש לפנות שטח מינימלי של 80/100 ס\"מ לצד האסלה.",
    severity: "medium",
    measurementFields: ["מרחק פנוי (ס\"מ)"],
    inspectionMethod: "מדידת המרחק הפנוי לצד האסלה.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מרחק פנוי", "אסלה"],
  },
  {
    id: "req-h-006",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.6",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "כיור",
    requirementTitle: "כיור נגיש בשירותים",
    practicalRequirement: "כיור: רוחב 30-40 ס\"מ, עומק 40-52 ס\"מ; גובה משטח עליון 80-85 ס\"מ; מרחב ברכיים לפי פרק 1.",
    defectText: "גובה הכיור חורג מהטווח 80-85 ס\"מ / אין מרחב ברכיים מתחת לכיור.",
    correctionText: "יש לכוון גובה הכיור ל-80-85 ס\"מ ולפנות מרחב ברכיים מתחתיו.",
    severity: "medium",
    measurementFields: ["גובה כיור (ס\"מ)", "מרחב ברכיים (כן/לא)"],
    inspectionMethod: "מדידת גובה הכיור ובדיקת מרחב הברכיים מתחתיו.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "כיור", "גובה"],
  },
  {
    id: "req-h-007",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.7",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מראה",
    requirementTitle: "גובה מראה בשירותים",
    practicalRequirement: "תחתית המראה תהיה בגובה לא יותר מ-90 ס\"מ; ראש המראה יהיה בגובה לפחות 175 ס\"מ.",
    defectText: "תחתית המראה גבוהה מ-90 ס\"מ / ראש המראה נמוך מ-175 ס\"מ.",
    correctionText: "יש להוריד את המראה כך שתחתיתה ב-90 ס\"מ לכל היותר וראשה ב-175 ס\"מ לפחות.",
    severity: "low",
    measurementFields: ["גובה תחתית מראה (ס\"מ)", "גובה ראש מראה (ס\"מ)"],
    inspectionMethod: "מדידת גובה תחתית וראש המראה.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מראה", "גובה"],
  },
  {
    id: "req-h-008",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "12.8",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "דלת תא שירותים",
    requirementTitle: "כיוון פתיחת דלת תא שירותים נגיש",
    practicalRequirement: "דלת תא השירותים הנגיש תיפתח כלפי חוץ. ניתן להשתמש בדלת הזזה כאשר פתיחה כלפי חוץ אינה אפשרית.",
    defectText: "דלת תא השירותים הנגיש נפתחת פנימה.",
    correctionText: "יש לשנות את כיוון הפתיחה של הדלת לכלפי חוץ, או להתקין דלת הזזה.",
    severity: "critical",
    measurementFields: ["כיוון פתיחה"],
    inspectionMethod: "בדיקת כיוון פתיחת הדלת.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "דלת", "פתיחה"],
  },
  {
    id: "req-h-009",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "13.1",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מקלחת נגישה",
    requirementTitle: "ממדי תא מקלחת נגיש",
    practicalRequirement: "תא מקלחת נגיש סוג 1 (פתוח): לפחות 1.20×1.50 מ'; פתח הכניסה לפחות 1.50 מ'.",
    defectText: "ממדי תא המקלחת קטנים מהנדרש.",
    correctionText: "יש להגדיל את תא המקלחת הנגיש לממדים הנדרשים.",
    severity: "critical",
    measurementFields: ["רוחב תא (מ')", "עומק תא (מ')", "רוחב פתח כניסה (מ')"],
    inspectionMethod: "מדידת ממדי תא המקלחת הנגיש.",
    appliesTo: ["restroom"],
    tags: ["מקלחת", "נגישה", "ממדים"],
  },
  {
    id: "req-h-010",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "13.2",
    category: "H. שירותי נגישות",
    categoryCode: "H",
    subCategory: "מקלחת נגישה",
    requirementTitle: "מושב מקלחת מתקפל",
    practicalRequirement: "במקלחת נגישה יהיה מושב מתקפל בגובה 45-50 ס\"מ מהרצפה.",
    defectText: "חסר מושב מתקפל / גובה המושב חורג מ-45-50 ס\"מ.",
    correctionText: "יש להתקין מושב מתקפל בגובה 45-50 ס\"מ במקלחת הנגישה.",
    severity: "medium",
    measurementFields: ["גובה מושב (ס\"מ)"],
    inspectionMethod: "בדיקת קיום מושב מתקפל ומדידת גובהו.",
    appliesTo: ["restroom"],
    tags: ["מקלחת", "מושב", "מתקפל"],
  },

  // ===== I: שילוט והכוונה =====
  {
    id: "req-i-001",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "4.1",
    category: "I. שילוט והכוונה",
    categoryCode: "I",
    subCategory: "גובה שלט",
    requirementTitle: "גובה מרכז שלט",
    practicalRequirement: "מרכז השלט יהיה בגובה 140-160 ס\"מ מהרצפה. תחתית השלט לפחות 100 ס\"מ; ראש השלט לא יעלה על 200 ס\"מ.",
    defectText: "גובה מרכז השלט חורג מהטווח 140-160 ס\"מ / השלט נמוך מ-100 ס\"מ / גבוה מ-200 ס\"מ.",
    correctionText: "יש להתאים את גובה השלט כך שמרכזו יהיה ב-140-160 ס\"מ.",
    severity: "low",
    measurementFields: ["גובה מרכז שלט (ס\"מ)", "גובה תחתית (ס\"מ)", "גובה ראש (ס\"מ)"],
    inspectionMethod: "מדידת גובה השלט מהרצפה.",
    appliesTo: ["signage", "interior"],
    tags: ["שילוט", "גובה", "שלט"],
  },
  {
    id: "req-i-002",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "4.2",
    category: "I. שילוט והכוונה",
    categoryCode: "I",
    subCategory: "מיקום שלט ליד דלת",
    requirementTitle: "מיקום שלט בדלת חדר",
    practicalRequirement: "שלט כניסה לחדר יוצב לצד ידית הדלת (צד הפתיחה), בגובה 140-160 ס\"מ.",
    defectText: "השלט ממוקם בצד שגוי (לא בצד ידית הדלת) / בגובה שגוי.",
    correctionText: "יש להעתיק את השלט לצד ידית הדלת בגובה הנכון.",
    severity: "low",
    measurementFields: ["מיקום שלט (כן/לא בצד ידית)", "גובה שלט (ס\"מ)"],
    inspectionMethod: "בדיקת מיקום השלט ביחס לידית הדלת ומדידת גובהו.",
    appliesTo: ["signage", "interior"],
    tags: ["שילוט", "דלת", "מיקום"],
  },
  {
    id: "req-i-003",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "4.3",
    category: "I. שילוט והכוונה",
    categoryCode: "I",
    subCategory: "שלט שירותים נגישים",
    requirementTitle: "שלט לשירותים נגישים",
    practicalRequirement: "שלט לשירותים נגישים יכלול את סמל הנכות הבינלאומי: לפחות 40 מ\"מ אם משולב, לפחות 100 מ\"מ אם נפרד.",
    defectText: "חסר שלט לשירותים נגישים / הסמל קטן מהנדרש.",
    correctionText: "יש להתקין שלט לשירותים הנגישים עם סמל נכות בגודל הנדרש.",
    severity: "medium",
    measurementFields: ["גודל סמל נכות (מ\"מ)"],
    inspectionMethod: "מדידת גודל סמל הנכות על השלט.",
    appliesTo: ["signage", "restroom"],
    tags: ["שילוט", "שירותים", "סמל נכות"],
  },
  {
    id: "req-i-004",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "4.4",
    category: "I. שילוט והכוונה",
    categoryCode: "I",
    subCategory: "שלטי הכוונה",
    requirementTitle: "שלטי הכוונה בצמתי מסדרונות",
    practicalRequirement: "בצמתי מסדרונות יהיו שלטי הכוונה לעבר מעליות ושירותים.",
    defectText: "חסרים שלטי הכוונה בצמת המסדרון לעבר מעלית / שירותים.",
    correctionText: "יש להתקין שלטי הכוונה ברורים בצמתי מסדרונות לכיוון מעלית ושירותים.",
    severity: "low",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום שלטי הכוונה בצמתי המסדרונות.",
    appliesTo: ["signage", "interior"],
    tags: ["שילוט", "הכוונה", "מסדרון", "כיוון"],
  },
  {
    id: "req-i-005",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "4.5",
    category: "I. שילוט והכוונה",
    categoryCode: "I",
    subCategory: "תוכן שלט",
    requirementTitle: "תוכן שלט: סמל וטקסט",
    practicalRequirement: "שלטים יכללו הן סמל גרפי והן טקסט מילולי. שלטים לשירותי גברים/נשים: בליטה עבה 1.0 מ\"מ לפחות.",
    defectText: "השלט חסר טקסט / חסר סמל גרפי / בליטה על שלטי שירותים קטנה מ-1.0 מ\"מ.",
    correctionText: "יש להוסיף טקסט/סמל לשלט ולהבטיח בליטה מינימלית על שלטי שירותים.",
    severity: "low",
    measurementFields: ["גובה בליטה (מ\"מ)"],
    inspectionMethod: "בדיקת תוכן השלט ומדידת גובה הבליטה.",
    appliesTo: ["signage"],
    tags: ["שילוט", "תוכן", "סמל", "טקסט"],
  },

  // ===== J: תקשורת ואמצעי התרעה =====
  {
    id: "req-j-001",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "5.1",
    category: "J. תקשורת ואמצעי התרעה",
    categoryCode: "J",
    subCategory: "מידע מישושי",
    requirementTitle: "מידע מישושי/ברייל",
    practicalRequirement: "מידע מישושי וכתב ברייל יוצגו בגובה 140-160 ס\"מ מהרצפה.",
    defectText: "כתב ברייל / מידע מישושי ממוקם מחוץ לטווח הגובה 140-160 ס\"מ.",
    correctionText: "יש להתקין את המידע המישושי/ברייל בגובה 140-160 ס\"מ מהרצפה.",
    severity: "low",
    measurementFields: ["גובה מידע מישושי (ס\"מ)"],
    inspectionMethod: "מדידת גובה המידע המישושי/ברייל.",
    appliesTo: ["communication", "signage"],
    tags: ["תקשורת", "ברייל", "מישושי", "גובה"],
  },
  {
    id: "req-j-002",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "5.2",
    category: "J. תקשורת ואמצעי התרעה",
    categoryCode: "J",
    subCategory: "מערכת השראה (לולאת T)",
    requirementTitle: "מערכת השראה אקוסטית (לולאת T)",
    practicalRequirement: "במקום שמחייב מערכת שמיעה מגברת, תוצב מערכת השראה (לולאת T) ותסומן בשלט T.",
    defectText: "חסרה מערכת השראה / חסר שלט T לסימון המערכת.",
    correctionText: "יש להתקין מערכת לולאת T ולסמנה בשלט T במקום הנדרש.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום מערכת ההשראה ושלט T.",
    appliesTo: ["communication"],
    tags: ["תקשורת", "השראה", "לולאת T", "שמיעה"],
  },
  {
    id: "req-j-003",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "5.3",
    category: "J. תקשורת ואמצעי התרעה",
    categoryCode: "J",
    subCategory: "מערכות כריזה",
    requirementTitle: "מערכות עזר לשמיעה",
    practicalRequirement: "מערכות עזר לשמיעה יהיו מסוג: IR, FM, או לולאת השראה. יש לסמן מקומות עם מערכות אלה.",
    defectText: "חסרה מערכת עזר לשמיעה / המקום אינו מסומן.",
    correctionText: "יש להתקין מערכת עזר לשמיעה ולסמן את המיקום בשילוט.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום מערכת עזר לשמיעה ושילוט.",
    appliesTo: ["communication"],
    tags: ["תקשורת", "שמיעה", "IR", "FM"],
  },
  {
    id: "req-j-004",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "5.4",
    category: "J. תקשורת ואמצעי התרעה",
    categoryCode: "J",
    subCategory: "אמצעי התרעה חזותיים",
    requirementTitle: "אמצעי התרעה חזותיים (פלאש/נורה)",
    practicalRequirement: "מערכות התרעה (אש, חירום) בבנייני ציבור יכללו גם אמצעי התרעה חזותיים (מהבהבים), בנוסף לאקוסטיים.",
    defectText: "מערכת ההתרעה חזותית חסרה / פועלת בצליל בלבד.",
    correctionText: "יש להוסיף אמצעי התרעה חזותיים (נוריות/מהבהבים) למערכת ההתרעה.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום מהבהבים/נוריות בנוסף לאמצעים האקוסטיים.",
    appliesTo: ["communication", "interior"],
    tags: ["התרעה", "חזותי", "מהבהב", "שמיעה"],
  },

  // ===== K: יחידות אכסון מיוחדות =====
  {
    id: "req-k-001",
    standardPart: 'ת"י 1918 חלק 5.1',
    clause: "2.1",
    category: "K. יחידות אכסון מיוחדות",
    categoryCode: "K",
    subCategory: "כניסה ליחידה",
    requirementTitle: "כניסה נגישה ליחידת אכסון",
    practicalRequirement: "כניסה ליחידת האכסון: רוחב דלת לפחות 0.90 מ'. מעל הכניסה כיסוי בממדי 1.30×1.70 מ' או 1.50×1.50 מ'. תאורה 100-200 לוקס.",
    defectText: "רוחב דלת הכניסה ליחידה פחות מ-0.90 מ' / חסר כיסוי / תאורה בלתי מספקת.",
    correctionText: "יש להרחיב את הדלת ל-0.90 מ', להוסיף כיסוי ולהתאים תאורה.",
    severity: "critical",
    measurementFields: ["רוחב דלת (מ')", "ממדי כיסוי (מ')", "תאורה (לוקס)"],
    inspectionMethod: "מדידת רוחב הדלת, ממדי הכיסוי ועוצמת התאורה.",
    appliesTo: ["apartment"],
    tags: ["יחידת אכסון", "כניסה", "דלת"],
  },
  {
    id: "req-k-002",
    standardPart: 'ת"י 1918 חלק 5.1',
    clause: "2.2",
    category: "K. יחידות אכסון מיוחדות",
    categoryCode: "K",
    subCategory: "דלתות פנימיות",
    requirementTitle: "רוחב דלתות פנימיות ביחידת אכסון",
    practicalRequirement: "רוחב כל דלת פנימית ביחידת האכסון יהיה לפחות 0.80 מ'.",
    defectText: "דלת פנימית ביחידת האכסון צרה מ-0.80 מ'.",
    correctionText: "יש להרחיב את הדלת הפנימית לרוחב לפחות 0.80 מ'.",
    severity: "critical",
    measurementFields: ["רוחב דלת (מ')", "מיקום הדלת"],
    inspectionMethod: "מדידת רוחב הפנוי של כל הדלתות הפנימיות ביחידה.",
    appliesTo: ["apartment"],
    tags: ["יחידת אכסון", "דלת פנימית", "רוחב"],
  },
  {
    id: "req-k-003",
    standardPart: 'ת"י 1918 חלק 5.1',
    clause: "2.3",
    category: "K. יחידות אכסון מיוחדות",
    categoryCode: "K",
    subCategory: "שטח תמרון",
    requirementTitle: "שטח תמרון ביחידת אכסון",
    practicalRequirement: "שטח תמרון לכיסא גלגלים (קוטר 1.50 מ') יהיה קיים בכל חדר ביחידה, למעט חדרי שירות.",
    defectText: "חסר שטח תמרון מספק (1.50 מ' × 1.50 מ') בחדר ביחידת האכסון.",
    correctionText: "יש לפנות שטח תמרון בקוטר 1.50 מ' בכל חדר.",
    severity: "medium",
    measurementFields: ["ממדי שטח תמרון (מ')"],
    inspectionMethod: "מדידת שטח התמרון בכל חדר.",
    appliesTo: ["apartment"],
    tags: ["יחידת אכסון", "תמרון", "כיסא גלגלים"],
  },
  {
    id: "req-k-004",
    standardPart: 'ת"י 1918 חלק 5.1',
    clause: "2.4",
    category: "K. יחידות אכסון מיוחדות",
    categoryCode: "K",
    subCategory: "ללא הפרשי גובה",
    requirementTitle: "ללא הפרשי גובה בין חדרים",
    practicalRequirement: "לא יהיו הפרשי גובה בין החדרים השונים ביחידת האכסון, אלא אם קיים מעלון/מעלית.",
    defectText: "קיים הפרש גובה בין חדרים ביחידה ללא מעלון/מעלית.",
    correctionText: "יש להסיר את הפרש הגובה או להתקין מעלון נגיש.",
    severity: "critical",
    measurementFields: ["גובה הפרש (ס\"מ)"],
    inspectionMethod: "בדיקת קיום הפרשי גובה בין החדרים.",
    appliesTo: ["apartment"],
    tags: ["יחידת אכסון", "הפרש גובה", "מעלון"],
  },

  // ===== L: יחידות דיור נגישות =====
  {
    id: "req-l-001",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "3.1",
    category: "L. יחידות דיור נגישות",
    categoryCode: "L",
    subCategory: "כניסה לדירה",
    requirementTitle: "כניסה נגישה לדירה",
    practicalRequirement: "דלת כניסה לדירה: רוחב לפחות 0.90 מ'; סף: לא יעלה על 1.5 ס\"מ; תאורה 100-200 לוקס.",
    defectText: "דלת הכניסה לדירה צרה מ-0.90 מ' / סף גבוה מ-1.5 ס\"מ / תאורה בלתי מספקת.",
    correctionText: "יש להרחיב את דלת הכניסה, להנמיך את הסף, ולהתאים את התאורה.",
    severity: "critical",
    measurementFields: ["רוחב דלת (מ')", "גובה סף (ס\"מ)", "תאורה (לוקס)"],
    inspectionMethod: "מדידת רוחב הדלת, גובה הסף ועוצמת התאורה.",
    appliesTo: ["apartment"],
    tags: ["דיור", "כניסה", "דלת"],
  },
  {
    id: "req-l-002",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "3.2",
    category: "L. יחידות דיור נגישות",
    categoryCode: "L",
    subCategory: "ספים בדירה",
    requirementTitle: "גובה ספים בדלתות הדירה",
    practicalRequirement: "בדירה נגישה: סף בין חדרים יבשים – 0; מעבר בין יבש-רטוב – עד 0.5 ס\"מ; בכניסה מחוץ – עד 1.5 ס\"מ.",
    defectText: "גובה הסף עולה על המותר (0 ס\"מ יבש-יבש / 0.5 ס\"מ יבש-רטוב / 1.5 ס\"מ כניסה).",
    correctionText: "יש להסיר/להנמיך את הספים לגבולות הנדרשים.",
    severity: "medium",
    measurementFields: ["גובה סף (ס\"מ)", "סוג מעבר"],
    inspectionMethod: "מדידת גבהי הספים בכל הדלתות.",
    appliesTo: ["apartment"],
    tags: ["דיור", "סף", "דלת"],
  },
  {
    id: "req-l-003",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "3.3",
    category: "L. יחידות דיור נגישות",
    categoryCode: "L",
    subCategory: "תריסים",
    requirementTitle: "תריסים חשמליים בדירה נגישה",
    practicalRequirement: "בדירה נגישה התריסים יהיו חשמליים (מופעלים חשמלית).",
    defectText: "התריסים בדירה הנגישה אינם חשמליים / הפעלה ידנית בלבד.",
    correctionText: "יש להחליף את התריסים לתריסים חשמליים.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת סוג הפעלת התריסים.",
    appliesTo: ["apartment"],
    tags: ["דיור", "תריסים", "חשמלי"],
  },
  {
    id: "req-l-004",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "3.4",
    category: "L. יחידות דיור נגישות",
    categoryCode: "L",
    subCategory: "דלתות פנימיות",
    requirementTitle: "רוחב דלתות פנימיות בדירה נגישה",
    practicalRequirement: "כל הדלתות הפנימיות בדירה נגישה: רוחב פנוי לפחות 0.80 מ'.",
    defectText: "דלת פנימית בדירה הנגישה צרה מ-0.80 מ'.",
    correctionText: "יש להרחיב את הדלת הפנימית לרוחב פנוי של לפחות 0.80 מ'.",
    severity: "critical",
    measurementFields: ["רוחב דלת (מ')", "מיקום הדלת"],
    inspectionMethod: "מדידת רוחב הפנוי של כל הדלתות הפנימיות.",
    appliesTo: ["apartment"],
    tags: ["דיור", "דלת פנימית", "רוחב"],
  },

  // ===== M: אמצעי אזהרה לעיוורים =====
  {
    id: "req-m-001",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "5.1",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "משטח אזהרה",
    requirementTitle: "משטח אזהרה מישושי",
    practicalRequirement: "משטח אזהרה: בליטות בצורת כיפה עם חתך טרפזי או מעוגל; ניגוד חזותי וניגוד מישושי ביחס לסביבה.",
    defectText: "חסר משטח אזהרה מישושי / הבליטות בצורה שגויה / חסר ניגוד חזותי.",
    correctionText: "יש להתקין משטח אזהרה מישושי עם בליטות כיפה בניגוד חזותי.",
    severity: "critical",
    measurementFields: ["קיום ניגוד חזותי (כן/לא)"],
    inspectionMethod: "בדיקה חזותית ומישושית של משטח האזהרה.",
    appliesTo: ["vision", "exterior", "interior"],
    tags: ["עיוורים", "אזהרה", "מישושי", "בליטות"],
  },
  {
    id: "req-m-002",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "5.2",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "פס הכוונה",
    requirementTitle: "פס הכוונה לעיוורים",
    practicalRequirement: "פס הכוונה (סוג 1): פסים מקבילים, באותה מישור הרצפה; ניגוד חזותי ומישושי; רוחב 55-65 ס\"מ לכיסוי נתיב הליכה.",
    defectText: "פס ההכוונה צר מ-55 ס\"מ / חסר ניגוד חזותי / הפסים אינם מקבילים.",
    correctionText: "יש להתקין פס הכוונה מסוג 1 ברוחב 55-65 ס\"מ בניגוד חזותי.",
    severity: "medium",
    measurementFields: ["רוחב פס הכוונה (ס\"מ)"],
    inspectionMethod: "מדידת רוחב פס ההכוונה ובדיקת ניגוד חזותי.",
    appliesTo: ["vision", "exterior", "interior"],
    tags: ["עיוורים", "הכוונה", "פס", "מישושי"],
  },
  {
    id: "req-m-003",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "5.3",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "אזהרה לפני מדרגות",
    requirementTitle: "רצועת אזהרה לפני מדרגות",
    practicalRequirement: "בכל כניסת מדרגות תהיה רצועת אזהרה מישושית ברוחב שלם של המדרגות, לאורך כל רוחבן.",
    defectText: "חסרה רצועת אזהרה מישושית לפני המדרגות / אינה לאורך כל רוחב המדרגות.",
    correctionText: "יש להתקין רצועת אזהרה מישושית לפני המדרגות לרוחב מלא.",
    severity: "critical",
    measurementFields: ["רוחב רצועה (ס\"מ)", "כיסוי מלא (כן/לא)"],
    inspectionMethod: "בדיקת קיום רצועת האזהרה ורוחבה לפני המדרגות.",
    appliesTo: ["vision", "exterior", "interior"],
    tags: ["עיוורים", "אזהרה", "מדרגות"],
  },
  {
    id: "req-m-004",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "5.4",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "אזהרה בנסיעה נעה",
    requirementTitle: "אזהרה לפני מדרגות נעות",
    practicalRequirement: "בראש ובתחתית מדרגות נעות תהיה רצועת אזהרה מישושית.",
    defectText: "חסרה רצועת אזהרה מישושית בראש/תחתית המדרגות הנעות.",
    correctionText: "יש להתקין רצועת אזהרה מישושית בראש ובתחתית המדרגות הנעות.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום רצועת אזהרה מישושית בנקודות הכניסה/יציאה של המדרגות הנעות.",
    appliesTo: ["vision", "interior"],
    tags: ["עיוורים", "מדרגות נעות", "אזהרה"],
  },
  {
    id: "req-m-005",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "5.5",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "חצייה",
    requirementTitle: "אמצעי אזהרה בחצייה רגלית",
    practicalRequirement: "בצמתי חצייה יהיו: רצועת אזהרה מישושית, ונורה/צליל להולכי רגל עם לקויות ראייה.",
    defectText: "חסרה רצועת אזהרה מישושית בחצייה / חסרים אמצעי חצייה נגישים.",
    correctionText: "יש להוסיף רצועת אזהרה מישושית ואמצעי חצייה נגישים בצמת.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום אמצעי אזהרה ונגישות בחצייה הרגלית.",
    appliesTo: ["vision", "exterior"],
    tags: ["עיוורים", "חצייה", "אזהרה"],
  },

  // ===== N: אמצעי הפעלה, רהיטים ועמדות שירות =====
  {
    id: "req-n-001",
    standardPart: 'ת"י 1918 חלק 1',
    clause: "3.1",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "גובה אמצעי הפעלה",
    requirementTitle: "גובה אמצעי הפעלה ובקרה",
    practicalRequirement: "אמצעי הפעלה (מתגים, לחצנים, שקעים) יהיו בגובה 85-110 ס\"מ מהרצפה.",
    defectText: "אמצעי הפעלה ממוקמים מחוץ לטווח 85-110 ס\"מ.",
    correctionText: "יש להעתיק את אמצעי ההפעלה לגובה הנדרש של 85-110 ס\"מ.",
    severity: "medium",
    measurementFields: ["גובה אמצעי הפעלה (ס\"מ)"],
    inspectionMethod: "מדידת גובה אמצעי ההפעלה.",
    appliesTo: ["interior", "exterior"],
    tags: ["הפעלה", "מתג", "גובה", "בקרה"],
  },
  {
    id: "req-n-002",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "14.1",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "דלפק שירות",
    requirementTitle: "גובה דלפק שירות נגיש",
    practicalRequirement: "חלק נגיש מדלפק/עמדת שירות: גובה לא יעלה על 85 ס\"מ; אורך לפחות 90 ס\"מ.",
    defectText: "גובה הדלפק/עמדת השירות עולה על 85 ס\"מ / אין חלק נגיש בגובה מתאים.",
    correctionText: "יש להנמיך חלק מהדלפק ל-85 ס\"מ ורוחב לפחות 90 ס\"מ.",
    severity: "medium",
    measurementFields: ["גובה החלק הנגיש (ס\"מ)", "אורך החלק הנגיש (ס\"מ)"],
    inspectionMethod: "מדידת גובה ואורך החלק הנגיש של הדלפק.",
    appliesTo: ["interior"],
    tags: ["דלפק", "עמדת שירות", "גובה"],
  },
  {
    id: "req-n-003",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "14.2",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "גישה לדלפק",
    requirementTitle: "גישה נגישה לעמדת שירות",
    practicalRequirement: "הגישה לדלפק/עמדת השירות תהיה נגישה לכיסא גלגלים: רוחב מעבר לפחות 0.90 מ'.",
    defectText: "המעבר לעמדת השירות חסום/צר מ-0.90 מ' לכיסא גלגלים.",
    correctionText: "יש לפנות נתיב גישה ברוחב לפחות 0.90 מ' לעמדת השירות.",
    severity: "critical",
    measurementFields: ["רוחב נתיב גישה (מ')"],
    inspectionMethod: "מדידת רוחב המעבר לעמדת השירות.",
    appliesTo: ["interior"],
    tags: ["דלפק", "גישה", "נתיב", "כיסא גלגלים"],
  },
  {
    id: "req-n-004",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.1",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "מקומות ישיבה נגישים",
    requirementTitle: "מספר מקומות לכיסאות גלגלים באולם",
    practicalRequirement: "יוקצו מקומות לכיסאות גלגלים: 1% ממקומות הישיבה, לפחות 2 מקומות ועד 25.",
    defectText: "אין מקומות מוקצים לכיסאות גלגלים / מספר המקומות נמוך מהנדרש.",
    correctionText: "יש להקצות מקומות לכיסאות גלגלים לפי הנוסחה הנדרשת.",
    severity: "critical",
    measurementFields: ["מספר כסאות כולל", "מספר מקומות כיסא גלגלים"],
    inspectionMethod: "ספירת מקומות הישיבה ומקומות כיסאות הגלגלים.",
    appliesTo: ["interior"],
    tags: ["אולם", "ישיבה", "כיסא גלגלים", "מקומות"],
  },
  {
    id: "req-n-005",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.2",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "ממדי מקום לכיסא גלגלים",
    requirementTitle: "ממדי מקום לכיסא גלגלים באולם",
    practicalRequirement: "מקום לכיסא גלגלים יהיה בממדים של 0.90×1.30 מ' לפחות, על משטח שטוח.",
    defectText: "המקום המוקצה לכיסא גלגלים קטן / על משטח משופע.",
    correctionText: "יש להגדיל את המקום ל-0.90×1.30 מ' ולהבטיח משטח שטוח.",
    severity: "medium",
    measurementFields: ["ממדי מקום (מ')"],
    inspectionMethod: "מדידת ממדי המקום המוקצה לכיסא גלגלים.",
    appliesTo: ["interior"],
    tags: ["אולם", "כיסא גלגלים", "ממדים"],
  },
  {
    id: "req-n-006",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.3",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "גישה לבמה",
    requirementTitle: "גישה נגישה לבמה/פודיום",
    practicalRequirement: "הגישה לבמה/פודיום תהיה נגישה לכיסא גלגלים: רמפה או מעלון.",
    defectText: "הגישה לבמה אפשרית רק דרך מדרגות / אין רמפה / מעלון.",
    correctionText: "יש להתקין רמפה נגישה או מעלון לגישה לבמה.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת נגישות הגישה לבמה.",
    appliesTo: ["interior"],
    tags: ["אולם", "במה", "גישה", "רמפה"],
  },
  {
    id: "req-n-007",
    standardPart: 'ת"י 1918 חלק 1',
    clause: "3.2",
    category: "N. אמצעי הפעלה, רהיטים ועמדות שירות",
    categoryCode: "N",
    subCategory: "ריהוט ועמדות עבודה",
    requirementTitle: "שולחן/עמדת עבודה נגישה",
    practicalRequirement: "שולחן/עמדת עבודה נגישה: גובה 72-80 ס\"מ; מרחב ברכיים לפחות 70 ס\"מ רוחב × 60 ס\"מ עומק × 67 ס\"מ גובה.",
    defectText: "גובה השולחן/העמדה חורג מ-72-80 ס\"מ / אין מרחב ברכיים מתאים.",
    correctionText: "יש לכוון את גובה העמדה ולהבטיח מרחב ברכיים נדרש.",
    severity: "low",
    measurementFields: ["גובה עמדה (ס\"מ)", "מרחב ברכיים (ס\"מ)"],
    inspectionMethod: "מדידת גובה העמדה ומרחב הברכיים מתחתיה.",
    appliesTo: ["interior"],
    tags: ["שולחן", "עמדת עבודה", "גובה", "ברכיים"],
  },
];

export const CATEGORIES = [
  { code: "A", label: "A. דרך נגישה ותנועה כללית" },
  { code: "B", label: "B. חניות נגישות" },
  { code: "C", label: "C. כניסה לבניין" },
  { code: "D", label: "D. פנים הבניין – מעברים ומסדרונות" },
  { code: "E", label: "E. דלתות ופתחים" },
  { code: "F", label: "F. מדרגות ומעקות" },
  { code: "G", label: "G. מעליות ומעלונים" },
  { code: "H", label: "H. שירותי נגישות" },
  { code: "I", label: "I. שילוט והכוונה" },
  { code: "J", label: "J. תקשורת ואמצעי התרעה" },
  { code: "K", label: "K. יחידות אכסון מיוחדות" },
  { code: "L", label: "L. יחידות דיור נגישות" },
  { code: "M", label: "M. אמצעי אזהרה לעיוורים" },
  { code: "N", label: "N. אמצעי הפעלה, רהיטים ועמדות שירות" },
];

export const PLACE_TYPE_LABELS: Record<string, string> = {
  exterior: "חצר/חוץ",
  interior: "פנים מבנה",
  restroom: "שירותים",
  parking: "חניה",
  "accessible-route": "דרך נגישה",
  apartment: "דיור",
  signage: "שילוט",
  vision: "ראייה",
  communication: "תקשורת",
};
