import { AccessibilityRequirement } from "./standards-types";

export const STANDARDS_DATA: AccessibilityRequirement[] = [
  // ===== A: דרך נגישה ותנועה כללית =====
  {
    id: "req-a-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.1",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רציפות דרך נגישה",
    requirementTitle: "רציפות הדרך הנגישה",
    practicalRequirement: "הדרך הנגישה תהיה רציפה מכניסת המגרש ועד כניסת הבניין, ללא מכשולים, הפרשי גובה או חסימות.",
    defectText: "הדרך הנגישה אינה רציפה / חסומה / אינה מאפשרת מעבר בטוח לאדם עם מוגבלות.",
    correctionText: "יש לפנות את המכשול / להשלים את הדרך הנגישה / לתקן את ההפרש כך שהדרך תהיה רציפה ובטוחה.",
    severity: "critical",
    measurementFields: ["אורך החסימה (מ')", "מיקום החסימה"],
    inspectionMethod: "בדיקה חזותית ומדידה לאורך מסלול הגישה מהכניסה למגרש עד הכניסה לבניין.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "רציפות", "מכשול", "גישה"],
  },
  {
    id: "req-a-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.2",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "רוחב דרך נגישה",
    requirementTitle: "רוחב מינימלי של דרך נגישה",
    practicalRequirement: "רוחב הדרך הנגישה יהיה לפחות 1.50 מ' לאורך כל המסלול.",
    defectText: "רוחב הדרך הנגישה נמוך מ-1.50 מ'.",
    correctionText: "יש להרחיב את הדרך הנגישה לרוחב מינימלי של 1.50 מ' לאורך כל המסלול.",
    severity: "critical",
    measurementFields: ["רוחב מדוד (מ')", "מיקום הצרות"],
    inspectionMethod: "מדידה בסרט מדידה בנקודות הצרות לאורך הדרך.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["דרך נגישה", "רוחב", "מינימום"],
  },
  {
    id: "req-a-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.3",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "שיפוע דרך נגישה",
    requirementTitle: "שיפוע רוחבי של דרך נגישה",
    practicalRequirement: "השיפוע הרוחבי של הדרך הנגישה לא יעלה על 2%.",
    defectText: "השיפוע הרוחבי של הדרך הנגישה עולה על 2%.",
    correctionText: "יש לתקן את פני המשטח כך שהשיפוע הרוחבי לא יעלה על 2%.",
    severity: "medium",
    measurementFields: ["שיפוע מדוד (%)"],
    inspectionMethod: "מדידת שיפוע באמצעות מד שיפוע (קלינומטר) בנקודות שונות.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "שיפוע", "רוחבי"],
  },
  {
    id: "req-a-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "5.4",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "גמר משטח",
    requirementTitle: "מרקם ויציבות משטח הדרך הנגישה",
    practicalRequirement: "משטח הדרך הנגישה יהיה יציב, חזק ולא החלקי. אין להשתמש בחצץ רופף או אבנים בלתי יציבות.",
    defectText: "משטח הדרך הנגישה אינו יציב / החלקי / לא אחיד.",
    correctionText: "יש להחליף או לתקן את מרקם המשטח לחומר יציב, חזק ולא החלקי.",
    severity: "medium",
    measurementFields: ["תיאור החומר"],
    inspectionMethod: "בדיקה חזותית ומישוש לאורך הדרך הנגישה.",
    appliesTo: ["exterior", "accessible-route"],
    tags: ["דרך נגישה", "משטח", "החלקה", "יציבות"],
  },
  {
    id: "req-a-005",
    standardPart: 'ת"י 1918 חלק 1',
    clause: "4.2",
    category: "A. דרך נגישה ותנועה כללית",
    categoryCode: "A",
    subCategory: "גובה פנוי",
    requirementTitle: "גובה פנוי מינימלי מעל הדרך הנגישה",
    practicalRequirement: "הגובה הפנוי לאורך כל הדרך הנגישה יהיה לפחות 2.00 מ'.",
    defectText: "הגובה הפנוי מעל הדרך הנגישה נמוך מ-2.00 מ'.",
    correctionText: "יש להסיר את המכשול/הבליטה שמפחיתה את הגובה הפנוי או לסמן אזהרה ולהסיט את המסלול.",
    severity: "critical",
    measurementFields: ["גובה פנוי מדוד (מ')"],
    inspectionMethod: "מדידת גובה פנוי בנקודות הנמוכות ביותר.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["גובה פנוי", "דרך נגישה"],
  },

  // ===== B: חניות נגישות =====
  {
    id: "req-b-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.1",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "מספר מקומות חניה נגישים",
    requirementTitle: "מספר מינימלי של מקומות חניה נגישים",
    practicalRequirement: "יש לסמן מספר מינימלי של מקומות חניה נגישים בהתאם לגודל חניון: 1 מקום לכל 25 מקומות חניה (לפחות 1).",
    defectText: "אין מספיק מקומות חניה נגישים מסומנים / אין כלל מקומות חניה נגישים.",
    correctionText: "יש לסמן ולהקצות מקומות חניה נגישים בהתאם לדרישות התקן.",
    severity: "critical",
    measurementFields: ["מספר מקומות חניה כולל", "מספר מקומות נגישים קיימים", "מספר מקומות נגישים נדרשים"],
    inspectionMethod: "ספירת מקומות חניה נגישים וסה\"כ מקומות בחניון.",
    appliesTo: ["parking"],
    tags: ["חניה", "נגיש", "מספר"],
  },
  {
    id: "req-b-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.2",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "ממדי מקום חניה נגיש",
    requirementTitle: "ממדי מקום חניה נגיש",
    practicalRequirement: "מקום חניה נגיש יהיה ברוחב 3.30 מ' לפחות (כולל פס אחיזה של 1.20 מ') ובאורך 5.00 מ' לפחות.",
    defectText: "מקום החניה הנגיש צר מדי / קצר מדי ואינו עומד בממדים הנדרשים.",
    correctionText: "יש לשנות את תיחום מקום החניה הנגיש לממדים הנדרשים: רוחב 3.30 מ' ואורך 5.00 מ' לפחות.",
    severity: "critical",
    measurementFields: ["רוחב מקום חניה (מ')", "אורך מקום חניה (מ')"],
    inspectionMethod: "מדידת ממדי מקום החניה הנגיש.",
    appliesTo: ["parking"],
    tags: ["חניה", "ממדים", "רוחב"],
  },
  {
    id: "req-b-003",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.3",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "סימון חניה נגישה",
    requirementTitle: "סימון וסמלי חניה נגישה",
    practicalRequirement: "מקום החניה הנגיש יסומן בסמל הנכות הבינלאומי על גבי הכביש ובשילוט אנכי.",
    defectText: "חסר סימון על הכביש / שילוט אנכי של חניה נגישה / הסימון דהוי ואינו קריא.",
    correctionText: "יש לסמן מחדש את מקום החניה הנגיש בסמל הנכות הבינלאומי ולהציב שילוט אנכי.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית של הסימון הרצפי והשילוט האנכי.",
    appliesTo: ["parking", "signage"],
    tags: ["חניה", "סימון", "שילוט", "סמל נכות"],
  },
  {
    id: "req-b-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "6.4",
    category: "B. חניות נגישות",
    categoryCode: "B",
    subCategory: "מיקום חניה נגישה",
    requirementTitle: "קרבת חניה נגישה לכניסה נגישה",
    practicalRequirement: "מקום החניה הנגיש יהיה קרוב ככל האפשר לכניסה הנגישה, ויחובר אליה בדרך נגישה.",
    defectText: "מקום החניה הנגיש אינו קרוב לכניסה הנגישה / אין דרך נגישה בין החניה לכניסה.",
    correctionText: "יש להקצות מקום חניה נגיש בסמוך לכניסה הנגישה ולהבטיח דרך נגישה רציפה ביניהם.",
    severity: "medium",
    measurementFields: ["מרחק מהכניסה (מ')"],
    inspectionMethod: "מדידת מרחק ובדיקת נגישות המסלול בין החניה לכניסה.",
    appliesTo: ["parking", "accessible-route"],
    tags: ["חניה", "מיקום", "כניסה נגישה"],
  },

  // ===== C: רמפות וכבשים =====
  {
    id: "req-c-001",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.1",
    category: "C. רמפות וכבשים",
    categoryCode: "C",
    subCategory: "שיפוע רמפה",
    requirementTitle: "שיפוע מרבי של רמפה",
    practicalRequirement: "שיפוע הרמפה לא יעלה על 1:12 (8.3%). רמפות קצרות עד 1.50 מ' – ניתן עד 1:8 (12.5%).",
    defectText: "שיפוע הרמפה תלול יותר מהמותר (מעל 1:12 לרמפות רגילות).",
    correctionText: "יש להקטין את שיפוע הרמפה ל-1:12 לכל היותר על ידי הארכת הרמפה.",
    severity: "critical",
    measurementFields: ["שיפוע מדוד (%)", "אורך הרמפה (מ')", "גובה ההפרש (מ')"],
    inspectionMethod: "מדידת שיפוע הרמפה בקלינומטר ומדידת אורך וגובה.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "שיפוע", "כבש"],
  },
  {
    id: "req-c-002",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.2",
    category: "C. רמפות וכבשים",
    categoryCode: "C",
    subCategory: "רוחב רמפה",
    requirementTitle: "רוחב מינימלי של רמפה",
    practicalRequirement: "רוחב הרמפה יהיה לפחות 1.20 מ' בין מעקות/אבני שפה.",
    defectText: "רוחב הרמפה נמוך מ-1.20 מ'.",
    correctionText: "יש להרחיב את הרמפה לרוחב מינימלי של 1.20 מ' בין המעקות.",
    severity: "critical",
    measurementFields: ["רוחב הרמפה (מ')"],
    inspectionMethod: "מדידת רוחב הרמפה בין שני המעקות/אבני השפה.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "רוחב", "מינימום"],
  },
  {
    id: "req-c-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "7.3",
    category: "C. רמפות וכבשים",
    categoryCode: "C",
    subCategory: "פודסט רמפה",
    requirementTitle: "פודסט (משטח מנוחה) ברמפה",
    practicalRequirement: "כל 9.00 מ' אורך רמפה יהיה פודסט בממדים של 1.50×1.50 מ' לפחות. פודסט בתחילת ובסוף הרמפה.",
    defectText: "חסר פודסט בתחילת/בסוף הרמפה / פודסט קטן מהנדרש / מרחק בין פודסטים עולה על 9 מ'.",
    correctionText: "יש להוסיף פודסט בגודל 1.50×1.50 מ' בתחילת ובסוף הרמפה ובכל 9 מ'.",
    severity: "medium",
    measurementFields: ["ממדי הפודסט (מ')", "מרחק בין פודסטים (מ')"],
    inspectionMethod: "מדידת ממדי הפודסט ומרחק בין הפודסטים.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "פודסט", "מנוחה"],
  },
  {
    id: "req-c-004",
    standardPart: 'ת"י 1918 חלק 2',
    clause: "7.4",
    category: "C. רמפות וכבשים",
    categoryCode: "C",
    subCategory: "מעקה ואבן שפה ברמפה",
    requirementTitle: "מעקה יד ואבן שפה ברמפה",
    practicalRequirement: "רמפות בגובה מעל 0.20 מ' יצוידו במעקות יד משני הצדדים. אבן שפה בגובה לפחות 0.10 מ' משני הצדדים.",
    defectText: "חסר מעקה יד בצד אחד או בשני הצדדים / חסרה אבן שפה / גובה אבן שפה קטן מ-0.10 מ'.",
    correctionText: "יש להתקין מעקות יד משני צידי הרמפה ואבני שפה בגובה לפחות 0.10 מ'.",
    severity: "medium",
    measurementFields: ["גובה מעקה (מ')", "גובה אבן שפה (מ')"],
    inspectionMethod: "בדיקה חזותית ומדידת גובה מעקה ואבן שפה.",
    appliesTo: ["exterior", "interior", "accessible-route"],
    tags: ["רמפה", "מעקה", "אבן שפה"],
  },

  // ===== D: מדרגות =====
  {
    id: "req-d-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "8.1",
    category: "D. מדרגות",
    categoryCode: "D",
    subCategory: "ממדי שלב מדרגה",
    requirementTitle: "גובה ועומק שלב מדרגה",
    practicalRequirement: "גובה שלב יהיה בין 0.10 מ' ל-0.18 מ'. עומק שלב לפחות 0.28 מ'. כל השלבים יהיו אחידים.",
    defectText: "גובה השלב חורג מהטווח המותר / שלבים אינם אחידים / עומק שלב קטן מ-0.28 מ'.",
    correctionText: "יש לתקן את ממדי השלבים לעמוד בדרישות התקן (גובה 0.10-0.18 מ', עומק 0.28 מ'+).",
    severity: "medium",
    measurementFields: ["גובה שלב (מ')", "עומק שלב (מ')", "מספר שלבים לא אחידים"],
    inspectionMethod: "מדידת מספר שלבים לאורך גרם המדרגות.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "שלב", "גובה", "עומק"],
  },
  {
    id: "req-d-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "8.2",
    category: "D. מדרגות",
    categoryCode: "D",
    subCategory: "רוחב מדרגות",
    requirementTitle: "רוחב מינימלי של גרם מדרגות",
    practicalRequirement: "גרם מדרגות נגיש יהיה ברוחב של לפחות 1.20 מ'.",
    defectText: "רוחב גרם המדרגות נמוך מ-1.20 מ'.",
    correctionText: "יש להרחיב את גרם המדרגות או להתקין מסילת תנועה עוקפת נגישה.",
    severity: "medium",
    measurementFields: ["רוחב גרם המדרגות (מ')"],
    inspectionMethod: "מדידת רוחב גרם המדרגות.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "רוחב"],
  },
  {
    id: "req-d-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "8.3",
    category: "D. מדרגות",
    categoryCode: "D",
    subCategory: "סימון קצה שלב",
    requirementTitle: "סימון קצה שלב מדרגה בצבע מנוגד",
    practicalRequirement: "קצה כל שלב מדרגה (הנוזה) יסומן ברצועת אנטי-החלקה/צבע מנוגד ברוחב לפחות 50 מ\"מ.",
    defectText: "חסר סימון קצה שלב מדרגה / הסימון דהוי ואינו ניכר.",
    correctionText: "יש להוסיף רצועת סימון בצבע מנוגד בקצה כל שלב ברוחב לפחות 50 מ\"מ.",
    severity: "low",
    measurementFields: ["רוחב רצועת סימון (מ\"מ)"],
    inspectionMethod: "בדיקה חזותית של סימוני הקצה לאורך גרם המדרגות.",
    appliesTo: ["interior", "exterior", "vision"],
    tags: ["מדרגות", "סימון", "ניגוד", "אנטי החלקה"],
  },
  {
    id: "req-d-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "8.4",
    category: "D. מדרגות",
    categoryCode: "D",
    subCategory: "נוזה מדרגה",
    requirementTitle: "נוזה מדרגה – בליטה אסורה",
    practicalRequirement: "הנוזה של שלב המדרגה לא תבלוט יותר מ-25 מ\"מ מעל הראיזר.",
    defectText: "הנוזה בולטת יותר מ-25 מ\"מ ועלולה לגרום להיתקלות.",
    correctionText: "יש לקצץ את הנוזה הבולטת ל-25 מ\"מ לכל היותר.",
    severity: "low",
    measurementFields: ["בליטת הנוזה (מ\"מ)"],
    inspectionMethod: "מדידת בליטת הנוזה.",
    appliesTo: ["interior", "exterior"],
    tags: ["מדרגות", "נוזה", "בליטה"],
  },

  // ===== E: דלתות ופתחים =====
  {
    id: "req-e-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.1",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "רוחב פתח דלת",
    requirementTitle: "רוחב מינימלי של פתח דלת נגיש",
    practicalRequirement: "רוחב הפתח החופשי של דלת נגישה יהיה לפחות 0.80 מ'.",
    defectText: "רוחב הפתח החופשי של הדלת נמוך מ-0.80 מ'.",
    correctionText: "יש להחליף את הדלת/המשקוף להשגת רוחב פתח חופשי של לפחות 0.80 מ'.",
    severity: "critical",
    measurementFields: ["רוחב פתח חופשי (מ')"],
    inspectionMethod: "מדידת רוחב הפתח החופשי של הדלת.",
    appliesTo: ["interior", "exterior", "accessible-route"],
    tags: ["דלת", "פתח", "רוחב"],
  },
  {
    id: "req-e-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.2",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "שטח תמרון בדלת",
    requirementTitle: "שטח תמרון בסמוך לדלת",
    practicalRequirement: "בצד הפתיחה של הדלת – שטח תמרון של 1.20×1.50 מ'. בצד הסגירה – 0.30 מ' לפחות מצד ידית הדלת.",
    defectText: "אין שטח תמרון מספיק בסמוך לדלת / הקיר גוסם לשטח התמרון.",
    correctionText: "יש לפנות שטח תמרון מספיק בסמוך לדלת בשני הצדדים.",
    severity: "medium",
    measurementFields: ["עומק שטח תמרון (מ')", "רוחב שטח תמרון (מ')"],
    inspectionMethod: "מדידת שטח התמרון משני צידי הדלת.",
    appliesTo: ["interior", "accessible-route"],
    tags: ["דלת", "תמרון", "כיסא גלגלים"],
  },
  {
    id: "req-e-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.3",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "כוח פתיחת דלת",
    requirementTitle: "כוח נדרש לפתיחת דלת",
    practicalRequirement: "הכוח הנדרש לפתיחת דלת נגישה לא יעלה על 22 ניוטון (דלת מרוסנת).",
    defectText: "הכוח הנדרש לפתיחת הדלת עולה על 22 ניוטון / הדלת כבדה מדי לפתיחה.",
    correctionText: "יש לכוון מחדש את מנגנון הסגירה האוטומטית להפחתת הכוח הנדרש לפתיחה.",
    severity: "medium",
    measurementFields: ["כוח פתיחה (ניוטון)"],
    inspectionMethod: "מדידת כוח פתיחה בדינמומטר.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "כוח פתיחה", "מנגנון סגירה"],
  },
  {
    id: "req-e-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "9.4",
    category: "E. דלתות ופתחים",
    categoryCode: "E",
    subCategory: "סף דלת",
    requirementTitle: "גובה סף דלת",
    practicalRequirement: "גובה הסף של דלת נגישה לא יעלה על 12 מ\"מ ויהיה מושפע (מפולס).",
    defectText: "הסף גבוה מ-12 מ\"מ / ישר ואינו מושפע / מהווה מכשול לכיסא גלגלים.",
    correctionText: "יש להוריד/להשפיע את הסף לגובה שלא עולה על 12 מ\"מ.",
    severity: "medium",
    measurementFields: ["גובה הסף (מ\"מ)"],
    inspectionMethod: "מדידת גובה הסף.",
    appliesTo: ["interior", "exterior"],
    tags: ["דלת", "סף", "מכשול"],
  },

  // ===== F: מעברים ושטחי תמרון =====
  {
    id: "req-f-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.1",
    category: "F. מעברים ושטחי תמרון",
    categoryCode: "F",
    subCategory: "רוחב מעבר",
    requirementTitle: "רוחב מינימלי של מעבר",
    practicalRequirement: "רוחב מעבר בין חסימות יהיה לפחות 0.90 מ'. מעבר הראשי יהיה לפחות 1.20 מ'.",
    defectText: "רוחב המעבר צר מ-0.90 מ' ואינו מאפשר מעבר לכיסא גלגלים.",
    correctionText: "יש לפנות/להרחיב את המעבר לרוחב מינימלי של 0.90 מ' (רצוי 1.20 מ').",
    severity: "critical",
    measurementFields: ["רוחב מדוד (מ')"],
    inspectionMethod: "מדידת רוחב המעבר בנקודות הצרות.",
    appliesTo: ["interior", "accessible-route"],
    tags: ["מעבר", "רוחב", "תמרון"],
  },
  {
    id: "req-f-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.2",
    category: "F. מעברים ושטחי תמרון",
    categoryCode: "F",
    subCategory: "שטח סיבוב כיסא גלגלים",
    requirementTitle: "שטח סיבוב לכיסא גלגלים",
    practicalRequirement: "שטח תמרון לסיבוב של 180° יהיה 1.50×1.50 מ' לפחות. לסיבוב T – 1.80×1.20 מ'.",
    defectText: "אין שטח סיבוב מספיק בקצות מעברים / ליד דלתות / בחדרים.",
    correctionText: "יש לפנות שטח תמרון של 1.50×1.50 מ' בנקודות הנדרשות.",
    severity: "medium",
    measurementFields: ["ממדי שטח תמרון (מ')"],
    inspectionMethod: "מדידת שטח הפנוי לתמרון כיסא גלגלים.",
    appliesTo: ["interior", "restroom"],
    tags: ["תמרון", "כיסא גלגלים", "סיבוב"],
  },
  {
    id: "req-f-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "10.3",
    category: "F. מעברים ושטחי תמרון",
    categoryCode: "F",
    subCategory: "מכשולים בגובה",
    requirementTitle: "זיהוי מכשולים תלויים",
    practicalRequirement: "מכשולים המובלטים בטווח גובה 0.68-2.00 מ' ואינם ניתנים לזיהוי בהליכה (גחים) חייבים בהגנה/סימון.",
    defectText: "קיים מכשול תלוי בגובה 0.68-2.00 מ' שלא ניתן לזיהוי על ידי מטה הליכה.",
    correctionText: "יש להוסיף מכשול שניתן לזיהוי עם מטה (לוח הגנה תחתון) או לשנות את מיקום המכשול.",
    severity: "medium",
    measurementFields: ["גובה תחתית מכשול (מ')", "תיאור המכשול"],
    inspectionMethod: "בדיקה חזותית לאיתור מכשולים גחים.",
    appliesTo: ["interior", "exterior", "vision"],
    tags: ["מכשול", "גובה", "עיוור", "מטה"],
  },

  // ===== G: מעליות ומעלונים =====
  {
    id: "req-g-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "11.1",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "ממדי תא מעלית",
    requirementTitle: "ממדים מינימליים של תא מעלית נגישה",
    practicalRequirement: "ממדי התא הפנימי יהיו לפחות 1.10 מ' עומק × 1.40 מ' רוחב. פתח הדלת: לפחות 0.80 מ'.",
    defectText: "ממדי תא המעלית קטנים מהנדרש / פתח הדלת צר מ-0.80 מ'.",
    correctionText: "יש לוודא שממדי המעלית עומדים בדרישות התקן או להתקין מעלית חדשה תקנית.",
    severity: "critical",
    measurementFields: ["עומק תא (מ')", "רוחב תא (מ')", "רוחב פתח (מ')"],
    inspectionMethod: "מדידת ממדי התא הפנימי ופתח הדלת.",
    appliesTo: ["interior"],
    tags: ["מעלית", "ממדים", "תא", "פתח"],
  },
  {
    id: "req-g-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "11.2",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "לחצני מעלית",
    requirementTitle: "לחצנים ושלט ברייל במעלית",
    practicalRequirement: "לחצני המעלית יהיו בגובה 0.90-1.20 מ'. ייכתב ברייל ומספרי בליטה על יד כל לחצן.",
    defectText: "לחצני המעלית גבוהים / נמוכים מדי / חסרה כתיבת ברייל / מספרי בליטה.",
    correctionText: "יש להתקין לחצנים בגובה 0.90-1.20 מ' ולהוסיף סימוני ברייל ומספרי בליטה.",
    severity: "medium",
    measurementFields: ["גובה לחצן עליון (מ')", "גובה לחצן תחתון (מ')"],
    inspectionMethod: "מדידת גובה הלחצנים ובדיקת ברייל.",
    appliesTo: ["interior", "vision"],
    tags: ["מעלית", "לחצן", "ברייל", "גובה"],
  },
  {
    id: "req-g-003",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "11.3",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "אינדיקציה קולית במעלית",
    requirementTitle: "הודעה קולית בהגעה לקומה",
    practicalRequirement: "בהגעת מעלית לקומה תושמע הודעה קולית עם מספר הקומה.",
    defectText: "חסרה הודעה קולית במעלית בהגעה לקומה.",
    correctionText: "יש להוסיף מערכת הודעה קולית שמכריזה את מספר הקומה בהגעה.",
    severity: "low",
    measurementFields: [],
    inspectionMethod: "בדיקה תפקודית – נסיעה בין הקומות ובדיקת ההכרזה.",
    appliesTo: ["interior", "vision", "communication"],
    tags: ["מעלית", "קולי", "הכרזה", "עיוור"],
  },
  {
    id: "req-g-004",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "11.4",
    category: "G. מעליות ומעלונים",
    categoryCode: "G",
    subCategory: "ריצוף שטח מנוחה מול מעלית",
    requirementTitle: "שטח מנוחה לפני מעלית",
    practicalRequirement: "בפני שער המעלית יהיה שטח פנוי של 1.50×1.50 מ' לפחות לתמרון כיסא גלגלים.",
    defectText: "שטח התמרון מול שער המעלית קטן מ-1.50×1.50 מ' / חסום על ידי ריהוט/מכשולים.",
    correctionText: "יש לפנות שטח תמרון של 1.50×1.50 מ' מול שערי המעלית.",
    severity: "medium",
    measurementFields: ["ממדי שטח תמרון (מ')"],
    inspectionMethod: "מדידת שטח הפנוי מול שערי המעלית.",
    appliesTo: ["interior"],
    tags: ["מעלית", "תמרון", "שטח פנוי"],
  },

  // ===== H: בתי שימוש נגישים =====
  {
    id: "req-h-001",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "12.1",
    category: "H. בתי שימוש נגישים",
    categoryCode: "H",
    subCategory: "ממדי חדר שירותים נגיש",
    requirementTitle: "ממדים מינימליים של חדר שירותים נגיש",
    practicalRequirement: "חדר שירותים נגיש יהיה בממדים של 2.20 מ' × 1.50 מ' לפחות (כולל שטח תמרון).",
    defectText: "חדר השירותים הנגיש קטן מהנדרש ואינו מאפשר תמרון מספיק.",
    correctionText: "יש להרחיב את חדר השירותים הנגיש לממדים המינימליים הנדרשים.",
    severity: "critical",
    measurementFields: ["אורך (מ')", "רוחב (מ')"],
    inspectionMethod: "מדידת ממדי חדר השירותים הנגיש.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "נגיש", "ממדים"],
  },
  {
    id: "req-h-002",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "12.2",
    category: "H. בתי שימוש נגישים",
    categoryCode: "H",
    subCategory: "מוט עזר אסלה",
    requirementTitle: "מוט עזר לצד האסלה",
    practicalRequirement: "יותקנו שני מוטות עזר: אחד קבוע ואחד מתקפל, בגובה 0.85 מ' מהרצפה, בצד חופשי ומנגד.",
    defectText: "חסר מוט עזר / אחד מהמוטות חסר / הגובה אינו תקני.",
    correctionText: "יש להתקין מוט קבוע ומוט מתקפל בגובה 0.85 מ' לצדי האסלה.",
    severity: "critical",
    measurementFields: ["גובה מוט קבוע (מ')", "גובה מוט מתקפל (מ')"],
    inspectionMethod: "בדיקה חזותית ומדידת גובה המוטות.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מוט עזר", "אסלה"],
  },
  {
    id: "req-h-003",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "12.3",
    category: "H. בתי שימוש נגישים",
    categoryCode: "H",
    subCategory: "כיור נגיש",
    requirementTitle: "גובה וממדי כיור נגיש",
    practicalRequirement: "גובה כיור מהרצפה: 0.85 מ'. מתחת לכיור יהיה מרווח פנוי לרגלי כיסא גלגלים: גובה 0.70 מ', עומק 0.45 מ'.",
    defectText: "גובה הכיור אינו תקני / אין מרווח מתחת לכיור / הצנרת חשופה וחמה.",
    correctionText: "יש לכוון גובה הכיור ל-0.85 מ' ולהבטיח מרווח פנוי ומבודד מתחתיו.",
    severity: "medium",
    measurementFields: ["גובה כיור (מ')", "גובה פנוי מתחת (מ')", "עומק פנוי (מ')"],
    inspectionMethod: "מדידת גובה הכיור והמרווח תחתיו.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "כיור", "גובה", "נגיש"],
  },
  {
    id: "req-h-004",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "12.4",
    category: "H. בתי שימוש נגישים",
    categoryCode: "H",
    subCategory: "לחצן מצוקה",
    requirementTitle: "לחצן מצוקה בשירותים נגישים",
    practicalRequirement: "יותקן לחצן מצוקה בשירותים הנגישים בגובה 0.40-0.50 מ' מהרצפה, הניתן להפעלה במצב שכיבה.",
    defectText: "חסר לחצן מצוקה / גובהו אינו תקני / לא ניתן להפעלה מהרצפה.",
    correctionText: "יש להתקין לחצן מצוקה בגובה 0.40-0.50 מ' ולחבר אותו למערכת מצוקה.",
    severity: "critical",
    measurementFields: ["גובה לחצן (מ')"],
    inspectionMethod: "מדידת גובה הלחצן ובדיקת תקינות המערכת.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "מצוקה", "לחצן", "בטיחות"],
  },
  {
    id: "req-h-005",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "12.5",
    category: "H. בתי שימוש נגישים",
    categoryCode: "H",
    subCategory: "גובה אסלה",
    requirementTitle: "גובה מושב אסלה",
    practicalRequirement: "גובה מושב האסלה יהיה בין 0.46 מ' ל-0.48 מ' מהרצפה.",
    defectText: "גובה מושב האסלה חורג מהטווח התקני 0.46-0.48 מ'.",
    correctionText: "יש לשנות את גובה האסלה (על ידי מושב מוגבה) לטווח הנדרש.",
    severity: "medium",
    measurementFields: ["גובה מושב אסלה (מ')"],
    inspectionMethod: "מדידת גובה מושב האסלה מהרצפה.",
    appliesTo: ["restroom"],
    tags: ["שירותים", "אסלה", "גובה"],
  },

  // ===== I: מקלחות וחדרי רחצה =====
  {
    id: "req-i-001",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "13.1",
    category: "I. מקלחות וחדרי רחצה",
    categoryCode: "I",
    subCategory: "מקלחת נגישה",
    requirementTitle: "ממדי מקלחת נגישה",
    practicalRequirement: "מקלחת נגישה תהיה בממדים של 1.50×1.50 מ' לפחות ועם גישה פתוחה (ללא מדרגה).",
    defectText: "מקלחת הנגישה קטנה / קיים סף מניעת כניסה / אין כיסא מקלחת.",
    correctionText: "יש להרחיב את המקלחת ולהסיר כל סף ולהתקין כיסא מקלחת.",
    severity: "critical",
    measurementFields: ["ממדי מקלחת (מ')"],
    inspectionMethod: "מדידת ממדי המקלחת ובדיקת הגישה.",
    appliesTo: ["restroom"],
    tags: ["מקלחת", "נגיש", "ממדים"],
  },
  {
    id: "req-i-002",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "13.2",
    category: "I. מקלחות וחדרי רחצה",
    categoryCode: "I",
    subCategory: "כיסא מקלחת",
    requirementTitle: "כיסא מקלחת קבוע/מתקפל",
    practicalRequirement: "יותקן כיסא מקלחת מתקפל בגובה 0.45-0.50 מ' מהרצפה בגודל 0.45×0.45 מ' לפחות.",
    defectText: "חסר כיסא מקלחת / הכיסא אינו יציב / גובהו אינו תקני.",
    correctionText: "יש להתקין כיסא מקלחת מתקפל תקני בגובה 0.45-0.50 מ'.",
    severity: "medium",
    measurementFields: ["גובה כיסא (מ')", "ממדי כיסא (מ')"],
    inspectionMethod: "בדיקה חזותית ומדידת גובה הכיסא.",
    appliesTo: ["restroom"],
    tags: ["מקלחת", "כיסא", "מתקפל"],
  },
  {
    id: "req-i-003",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "13.3",
    category: "I. מקלחות וחדרי רחצה",
    categoryCode: "I",
    subCategory: "זרנוק ידני",
    requirementTitle: "זרנוק ידני גמיש במקלחת",
    practicalRequirement: "יותקן ראש מקלחת ידני גמיש (זרנוק) עם שרשרת/צינור באורך 1.50 מ' לפחות.",
    defectText: "חסר זרנוק ידני גמיש / הזרנוק קצר מ-1.50 מ'.",
    correctionText: "יש להתקין זרנוק ידני גמיש באורך לפחות 1.50 מ'.",
    severity: "medium",
    measurementFields: ["אורך זרנוק (מ')"],
    inspectionMethod: "בדיקת קיום ואורך הזרנוק הידני.",
    appliesTo: ["restroom", "apartment"],
    tags: ["מקלחת", "זרנוק", "ידני"],
  },
  {
    id: "req-i-004",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "13.4",
    category: "I. מקלחות וחדרי רחצה",
    categoryCode: "I",
    subCategory: "מוטות עזר מקלחת",
    requirementTitle: "מוטות עזר במקלחת נגישה",
    practicalRequirement: "יותקנו מוטות עזר אופקיים ו/או אלכסוניים בתוך המקלחת לאחיזה ויציבות.",
    defectText: "חסרים מוטות עזר במקלחת / מוטות עזר אינם יציבים.",
    correctionText: "יש להתקין מוטות עזר תקניים במקלחת.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית ובדיקת יציבות המוטות.",
    appliesTo: ["restroom", "apartment"],
    tags: ["מקלחת", "מוטות עזר", "אחיזה"],
  },

  // ===== J: מטבחים ויחידות דיור =====
  {
    id: "req-j-001",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "14.1",
    category: "J. מטבחים ויחידות דיור",
    categoryCode: "J",
    subCategory: "גובה משטח עבודה",
    requirementTitle: "גובה משטח עבודה במטבח נגיש",
    practicalRequirement: "משטח העבודה במטבח נגיש יהיה בגובה 0.85 מ' מהרצפה. מתחתיו מרווח פנוי של 0.70 מ'.",
    defectText: "גובה משטח העבודה אינו תקני / אין מרווח מתחת לאחד ממרכיבי המטבח.",
    correctionText: "יש לכוון גובה משטח העבודה ל-0.85 מ' ולהבטיח מרווח פנוי מתחתיו.",
    severity: "medium",
    measurementFields: ["גובה משטח (מ')", "גובה פנוי מתחת (מ')"],
    inspectionMethod: "מדידת גובה משטח העבודה ובדיקת המרווח תחתיו.",
    appliesTo: ["apartment"],
    tags: ["מטבח", "גובה", "משטח עבודה"],
  },
  {
    id: "req-j-002",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "14.2",
    category: "J. מטבחים ויחידות דיור",
    categoryCode: "J",
    subCategory: "ממדי מטבח נגיש",
    requirementTitle: "מרחב תמרון במטבח",
    practicalRequirement: "יהיה מרחב תמרון של 1.50×1.50 מ' לפחות בפנים המטבח לסיבוב כיסא גלגלים.",
    defectText: "אין מרחב תמרון מספיק במטבח לסיבוב כיסא גלגלים.",
    correctionText: "יש לפנות שטח תמרון של לפחות 1.50×1.50 מ' בתוך המטבח.",
    severity: "medium",
    measurementFields: ["ממדי מרחב תמרון (מ')"],
    inspectionMethod: "מדידת שטח הפנוי לתמרון בתוך המטבח.",
    appliesTo: ["apartment"],
    tags: ["מטבח", "תמרון", "כיסא גלגלים"],
  },
  {
    id: "req-j-003",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "14.3",
    category: "J. מטבחים ויחידות דיור",
    categoryCode: "J",
    subCategory: "כניסה ליחידת דיור",
    requirementTitle: "כניסה נגישה ליחידת דיור",
    practicalRequirement: "הכניסה ליחידת הדיור תהיה נגישה: פתח לפחות 0.80 מ', ללא סף, שטח תמרון מול הדלת.",
    defectText: "פתח הכניסה ליחידה צר / קיים סף / אין שטח תמרון.",
    correctionText: "יש להרחיב פתח הכניסה ולהסיר את הסף וליצור שטח תמרון.",
    severity: "critical",
    measurementFields: ["רוחב פתח (מ')", "גובה סף (מ\"מ)"],
    inspectionMethod: "מדידת פתח הכניסה ובדיקת הסף.",
    appliesTo: ["apartment", "accessible-route"],
    tags: ["דיור", "כניסה", "דלת", "סף"],
  },
  {
    id: "req-j-004",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "14.4",
    category: "J. מטבחים ויחידות דיור",
    categoryCode: "J",
    subCategory: "חיבורי חשמל ותשתית",
    requirementTitle: "גובה שקעים ומפסקים ביחידת דיור",
    practicalRequirement: "שקעי חשמל יהיו בגובה 0.40-0.60 מ'. מפסקי תאורה ייכתבו בגובה 0.90-1.20 מ'.",
    defectText: "שקעי חשמל או מפסקי תאורה נמצאים מחוץ לטווח הגובה הנגיש.",
    correctionText: "יש להוסיף שקעים ומפסקים בגובה הנגיש הנדרש.",
    severity: "low",
    measurementFields: ["גובה שקע (מ')", "גובה מפסק (מ')"],
    inspectionMethod: "מדידת גובה שקעים ומפסקים.",
    appliesTo: ["apartment"],
    tags: ["דיור", "שקע", "מפסק", "גובה"],
  },

  // ===== K: מאחזי יד =====
  {
    id: "req-k-001",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "15.1",
    category: "K. מאחזי יד",
    categoryCode: "K",
    subCategory: "גובה מאחז יד",
    requirementTitle: "גובה מאחז יד במדרגות ורמפות",
    practicalRequirement: "מאחז היד יהיה בגובה 0.90 מ' (± 0.05 מ') מהרצפה / שלב המדרגה.",
    defectText: "מאחז היד גבוה/נמוך מדי מהגובה הנדרש (0.85-0.95 מ').",
    correctionText: "יש לכוון/להחליף את מאחז היד לגובה הנדרש.",
    severity: "medium",
    measurementFields: ["גובה מאחז יד (מ')"],
    inspectionMethod: "מדידת גובה מאחז היד.",
    appliesTo: ["interior", "exterior"],
    tags: ["מאחז יד", "גובה", "מדרגות", "רמפה"],
  },
  {
    id: "req-k-002",
    standardPart: 'ת"י 1918 חלק 3.1',
    clause: "15.2",
    category: "K. מאחזי יד",
    categoryCode: "K",
    subCategory: "הארכת מאחז יד",
    requirementTitle: "הארכת מאחז יד מעבר לראשית/סיום",
    practicalRequirement: "מאחז היד יוארך ב-0.30 מ' לפחות מעבר לשלב הראשון ולאחרון, ומעבר לראשית/סיום הרמפה.",
    defectText: "מאחז היד אינו מוארך מעבר לנקודת ההתחלה/סיום של המדרגות/רמפה.",
    correctionText: "יש להאריך את מאחז היד ב-0.30 מ' מעבר לשלב הראשון והאחרון ומעבר לרמפה.",
    severity: "low",
    measurementFields: ["הארכה ראשית (מ')", "הארכה סופית (מ')"],
    inspectionMethod: "מדידת הארכת מאחז היד.",
    appliesTo: ["interior", "exterior"],
    tags: ["מאחז יד", "הארכה", "מדרגות", "רמפה"],
  },
  {
    id: "req-k-003",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "15.3",
    category: "K. מאחזי יד",
    categoryCode: "K",
    subCategory: "קוטר מאחז יד",
    requirementTitle: "קוטר וצורת מאחז יד",
    practicalRequirement: "קוטר מאחז היד יהיה בין 35 מ\"מ ל-50 מ\"מ. הצורה תאפשר אחיזה נוחה.",
    defectText: "קוטר מאחז היד חורג מהטווח הנדרש / הצורה אינה נוחה לאחיזה.",
    correctionText: "יש להחליף את מאחז היד לקוטר 35-50 מ\"מ.",
    severity: "low",
    measurementFields: ["קוטר מאחז יד (מ\"מ)"],
    inspectionMethod: "מדידת קוטר מאחז היד.",
    appliesTo: ["interior", "exterior", "restroom"],
    tags: ["מאחז יד", "קוטר", "אחיזה"],
  },
  {
    id: "req-k-004",
    standardPart: 'ת"י 1918 חלק 5.2',
    clause: "15.4",
    category: "K. מאחזי יד",
    categoryCode: "K",
    subCategory: "יציבות מאחז יד",
    requirementTitle: "יציבות מאחז היד",
    practicalRequirement: "מאחז היד יהיה יציב וחזק, עמיד בעומס של לפחות 135 ק\"ג בכיוון אופקי.",
    defectText: "מאחז היד מתנדנד / חלש / אינו יציב.",
    correctionText: "יש לחזק/להחליף את מאחז היד לעמידה בעומסים הנדרשים.",
    severity: "critical",
    measurementFields: [],
    inspectionMethod: "בדיקת יציבות על ידי הפעלת כוח ידני.",
    appliesTo: ["interior", "exterior", "restroom"],
    tags: ["מאחז יד", "יציבות", "בטיחות"],
  },

  // ===== L: שילוט ותקשורת =====
  {
    id: "req-l-001",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "16.1",
    category: "L. שילוט ותקשורת",
    categoryCode: "L",
    subCategory: "שילוט כניסה נגישה",
    requirementTitle: "שילוט לכניסה הנגישה",
    practicalRequirement: "כניסה נגישה תסומן בסמל הנכות הבינלאומי הנראה בבירור מהכניסה הראשית.",
    defectText: "חסר שילוט לכניסה הנגישה / השלט לא נראה מהכניסה הראשית.",
    correctionText: "יש להציב שלט עם סמל הנכות הבינלאומי הגדול ממוקם לכיוון הכניסה הנגישה.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית – האם השלט נראה בבירור מהכניסה הראשית.",
    appliesTo: ["exterior", "signage"],
    tags: ["שילוט", "כניסה נגישה", "סמל נכות"],
  },
  {
    id: "req-l-002",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "16.2",
    category: "L. שילוט ותקשורת",
    categoryCode: "L",
    subCategory: "גובה שלט",
    requirementTitle: "גובה שלטים מידעיים",
    practicalRequirement: "שלטים מידעיים יהיו בגובה 1.40-1.60 מ' ממרכז השלט לרצפה.",
    defectText: "השלטים גבוהים / נמוכים מדי מהטווח הנדרש.",
    correctionText: "יש למקם מחדש את השלטים בגובה 1.40-1.60 מ' ממרכז השלט.",
    severity: "low",
    measurementFields: ["גובה מרכז שלט (מ')"],
    inspectionMethod: "מדידת גובה מרכז השלטים.",
    appliesTo: ["interior", "signage"],
    tags: ["שילוט", "גובה", "מידע"],
  },
  {
    id: "req-l-003",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "16.3",
    category: "L. שילוט ותקשורת",
    categoryCode: "L",
    subCategory: "ניגוד צבעים בשילוט",
    requirementTitle: "ניגוד צבעים בשלטים",
    practicalRequirement: "שלטים יהיו בניגוד צבעים של לפחות 70% בין הטקסט לרקע.",
    defectText: "ניגוד הצבעים בשלטים אינו מספיק / טקסט קשה לקריאה.",
    correctionText: "יש לשנות את צבעי השלט להשגת ניגוד של לפחות 70%.",
    severity: "low",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית של ניגוד הצבעים בשלטים.",
    appliesTo: ["interior", "exterior", "signage", "vision"],
    tags: ["שילוט", "ניגוד צבעים", "קריאות"],
  },
  {
    id: "req-l-004",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "16.4",
    category: "L. שילוט ותקשורת",
    categoryCode: "L",
    subCategory: "שילוט ברייל",
    requirementTitle: "שילוט ברייל ובדפוס מוגבה",
    practicalRequirement: "שלטי כניסה לחדרים, מעליות וחדרי שירותים יכללו גם טקסט ברייל ודפוס מוגבה.",
    defectText: "חסר שילוט ברייל / טקסט מוגבה בשלטים הנדרשים.",
    correctionText: "יש להוסיף שילוט ברייל ודפוס מוגבה על השלטים הרלוונטיים.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית ומישוש לנוכחות ברייל.",
    appliesTo: ["interior", "signage", "vision"],
    tags: ["שילוט", "ברייל", "דפוס מוגבה", "עיוור"],
  },

  // ===== M: אמצעי אזהרה לעיוורים =====
  {
    id: "req-m-001",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "17.1",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "פסי אזהרה",
    requirementTitle: "פסי אזהרה לפני מכשול/הפרש גובה",
    practicalRequirement: "פסי אזהרה מישושיים יותקנו לפני ראשי מדרגות, רמפות ומכשולים בשטח הציבורי.",
    defectText: "חסרים פסי אזהרה מישושיים לפני ראש המדרגות / רמפה / מכשול.",
    correctionText: "יש להתקין פסי אזהרה מישושיים (בולטות חצי כדוריות) לפני כל נקודה מסוכנת.",
    severity: "critical",
    measurementFields: ["עומק פסי אזהרה (מ')"],
    inspectionMethod: "בדיקה חזותית ומישוש לנוכחות פסי אזהרה.",
    appliesTo: ["exterior", "interior", "vision"],
    tags: ["עיוור", "פסי אזהרה", "מישוש", "בטיחות"],
  },
  {
    id: "req-m-002",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "17.2",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "פסי הכוונה",
    requirementTitle: "פסי הכוונה מישושיים",
    practicalRequirement: "פסי הכוונה (בולטות קוויות) יותקנו לאורך מסלול הכניסה הנגישה ולכיוון שירותים ומעלית.",
    defectText: "חסרים פסי הכוונה מישושיים / הרצף של פסי ההכוונה נקטע.",
    correctionText: "יש להוסיף פסי הכוונה רציפים מהכניסה אל יעדים עיקריים.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית ומישוש לנוכחות ורציפות פסי ההכוונה.",
    appliesTo: ["exterior", "interior", "vision"],
    tags: ["עיוור", "פסי הכוונה", "מישוש"],
  },
  {
    id: "req-m-003",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "17.3",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "ניגוד צבעים של פסים",
    requirementTitle: "ניגוד צבעים של פסי אזהרה/הכוונה",
    practicalRequirement: "פסי האזהרה וההכוונה יהיו בצבע מנוגד למשטח שבו הם מותקנים.",
    defectText: "פסי האזהרה/ההכוונה אינם ניכרים – ניגוד הצבעים אינו מספיק.",
    correctionText: "יש להחליף/לצבוע מחדש את הפסים בצבע בניגוד גבוה למשטח.",
    severity: "low",
    measurementFields: [],
    inspectionMethod: "בדיקה חזותית של ניגוד הצבעים.",
    appliesTo: ["exterior", "interior", "vision"],
    tags: ["עיוור", "פסי אזהרה", "ניגוד צבעים"],
  },
  {
    id: "req-m-004",
    standardPart: 'ת"י 1918 חלק 6',
    clause: "17.4",
    category: "M. אמצעי אזהרה לעיוורים",
    categoryCode: "M",
    subCategory: "אזהרה בצלב כבישה",
    requirementTitle: "אמצעי אזהרה בצלב כבישה",
    practicalRequirement: "בצלב כבישה נגיש: פסי אזהרה לפני ירידת המדרכה ואות קולי / מישושי של הרמזור.",
    defectText: "חסרים פסי אזהרה / אות קולי בצלב הכבישה.",
    correctionText: "יש להוסיף פסי אזהרה ואות קולי/מישושי בצלב הכבישה.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקה בשטח של אמצעי האזהרה בצלב הכבישה.",
    appliesTo: ["exterior", "vision"],
    tags: ["עיוור", "צלב כבישה", "רמזור", "קולי"],
  },

  // ===== N: עמדות שירות ודלפקים =====
  {
    id: "req-n-001",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "18.1",
    category: "N. עמדות שירות ודלפקים",
    categoryCode: "N",
    subCategory: "גובה דלפק נגיש",
    requirementTitle: "גובה דלפק נגיש",
    practicalRequirement: "לפחות חלק מדלפק השירות יהיה בגובה 0.85 מ' עם מרווח פנוי מתחת (0.70 מ').",
    defectText: "הדלפק גבוה מדי / אין חלק נגיש בגובה 0.85 מ'.",
    correctionText: "יש להוסיף/להוריד חלק מהדלפק לגובה 0.85 מ' עם מרווח פנוי מתחת.",
    severity: "medium",
    measurementFields: ["גובה דלפק (מ')", "גובה פנוי מתחת (מ')"],
    inspectionMethod: "מדידת גובה הדלפק ובדיקת המרווח.",
    appliesTo: ["interior"],
    tags: ["דלפק", "שירות", "גובה", "נגיש"],
  },
  {
    id: "req-n-002",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "18.2",
    category: "N. עמדות שירות ודלפקים",
    categoryCode: "N",
    subCategory: "עמדת ATM נגישה",
    requirementTitle: "כספומט/מכשיר שירות עצמי נגיש",
    practicalRequirement: "לחצני עמדת השירות יהיו בגובה 0.90-1.20 מ'. שטח תמרון של 1.50×1.50 מ' מולה.",
    defectText: "לחצני הכספומט/עמדת שירות מחוץ לטווח הגובה / אין שטח תמרון.",
    correctionText: "יש להתאים את עמדת השירות לגובה הנדרש ולפנות שטח תמרון מולה.",
    severity: "medium",
    measurementFields: ["גובה לחצן עליון (מ')", "גובה לחצן תחתון (מ')"],
    inspectionMethod: "מדידת גובה לחצנים ושטח תמרון.",
    appliesTo: ["interior", "exterior"],
    tags: ["כספומט", "שירות עצמי", "גובה", "תמרון"],
  },
  {
    id: "req-n-003",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "18.3",
    category: "N. עמדות שירות ודלפקים",
    categoryCode: "N",
    subCategory: "לולאת השראה",
    requirementTitle: "לולאת השראה לכבדי שמיעה",
    practicalRequirement: "בדלפקי שירות ייכתב שלט על קיום לולאת השראה. הלולאה תהיה פעילה ומסומנת.",
    defectText: "חסרה לולאת השראה / הלולאה לא פעילה / אין שילוט על קיומה.",
    correctionText: "יש להתקין לולאת השראה ולסמנה בשלט T הסטנדרטי.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת קיום ותפקוד לולאת ההשראה.",
    appliesTo: ["interior", "communication"],
    tags: ["לולאת השראה", "שמיעה", "דלפק"],
  },
  {
    id: "req-n-004",
    standardPart: 'ת"י 1918 חלק 4',
    clause: "18.4",
    category: "N. עמדות שירות ודלפקים",
    categoryCode: "N",
    subCategory: "גישה לעמדת שירות",
    requirementTitle: "גישה נגישה לעמדת שירות",
    practicalRequirement: "הגישה לדלפק/עמדת השירות תהיה נגישה לכיסא גלגלים: רוחב מעבר לפחות 0.90 מ'.",
    defectText: "המעבר לעמדת השירות חסום/צר מ-0.90 מ' לכיסא גלגלים.",
    correctionText: "יש לפנות נתיב גישה ברוחב לפחות 0.90 מ' לעמדת השירות.",
    severity: "critical",
    measurementFields: ["רוחב נתיב גישה (מ')"],
    inspectionMethod: "מדידת רוחב המעבר לעמדת השירות.",
    appliesTo: ["interior"],
    tags: ["דלפק", "גישה", "נתיב", "כיסא גלגלים"],
  },

  // ===== O: אולמות ומקומות ישיבה =====
  {
    id: "req-o-001",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.1",
    category: "O. אולמות ומקומות ישיבה",
    categoryCode: "O",
    subCategory: "מקומות ישיבה נגישים",
    requirementTitle: "מספר מקומות לכיסאות גלגלים באולם",
    practicalRequirement: "יוקצו מקומות לכיסאות גלגלים: 1% ממקומות הישיבה, לפחות 2 מקומות ועד 25.",
    defectText: "אין מקומות מוקצים לכיסאות גלגלים / מספר המקומות נמוך מהנדרש.",
    correctionText: "יש להקצות מקומות לכיסאות גלגלים לפי הנוסחה הנדרשת.",
    severity: "critical",
    measurementFields: ["מספר כסאות כולל", "מספר מקומות כיסא גלגלים"],
    inspectionMethod: "ספירת מקומות הישיבה ומקומות כיסאות הגלגלים.",
    appliesTo: ["interior"],
    tags: ["אולם", "ישיבה", "כיסא גלגלים", "מקומות"],
  },
  {
    id: "req-o-002",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.2",
    category: "O. אולמות ומקומות ישיבה",
    categoryCode: "O",
    subCategory: "ממדי מקום לכיסא גלגלים",
    requirementTitle: "ממדי מקום לכיסא גלגלים באולם",
    practicalRequirement: "מקום לכיסא גלגלים יהיה בממדים של 0.90×1.30 מ' לפחות, על משטח שטוח.",
    defectText: "המקום המוקצה לכיסא גלגלים קטן / על משטח משופע.",
    correctionText: "יש להגדיל את המקום ל-0.90×1.30 מ' ולהבטיח משטח שטוח.",
    severity: "medium",
    measurementFields: ["ממדי מקום (מ')"],
    inspectionMethod: "מדידת ממדי המקום המוקצה לכיסא גלגלים.",
    appliesTo: ["interior"],
    tags: ["אולם", "כיסא גלגלים", "ממדים"],
  },
  {
    id: "req-o-003",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.3",
    category: "O. אולמות ומקומות ישיבה",
    categoryCode: "O",
    subCategory: "פיזור מקומות נגישים",
    requirementTitle: "פיזור מקומות נגישים באולם",
    practicalRequirement: "מקומות כיסאות הגלגלים יהיו מפוזרים בחלקים שונים של האולם ולא מרוכזים כולם במקום אחד.",
    defectText: "כל מקומות כיסאות הגלגלים מרוכזים בקצה אחד של האולם.",
    correctionText: "יש לפזר את מקומות כיסאות הגלגלים לאורך האולם.",
    severity: "low",
    measurementFields: [],
    inspectionMethod: "בדיקת מיקום ופיזור מקומות כיסאות הגלגלים.",
    appliesTo: ["interior"],
    tags: ["אולם", "פיזור", "כיסא גלגלים"],
  },
  {
    id: "req-o-004",
    standardPart: 'ת"י 1918 חלק 3.2',
    clause: "19.4",
    category: "O. אולמות ומקומות ישיבה",
    categoryCode: "O",
    subCategory: "גישה לבמה",
    requirementTitle: "גישה נגישה לבמה/פודיום",
    practicalRequirement: "הגישה לבמה/פודיום תהיה נגישה לכיסא גלגלים: רמפה או מעלון.",
    defectText: "הגישה לבמה אפשרית רק דרך מדרגות / אין רמפה / מעלון.",
    correctionText: "יש להתקין רמפה נגישה או מעלון לגישה לבמה.",
    severity: "medium",
    measurementFields: [],
    inspectionMethod: "בדיקת נגישות הגישה לבמה.",
    appliesTo: ["interior"],
    tags: ["אולם", "במה", "גישה", "רמפה"],
  },
];

export const CATEGORIES = [
  { code: "A", label: "A. דרך נגישה ותנועה כללית" },
  { code: "B", label: "B. חניות נגישות" },
  { code: "C", label: "C. רמפות וכבשים" },
  { code: "D", label: "D. מדרגות" },
  { code: "E", label: "E. דלתות ופתחים" },
  { code: "F", label: "F. מעברים ושטחי תמרון" },
  { code: "G", label: "G. מעליות ומעלונים" },
  { code: "H", label: "H. בתי שימוש נגישים" },
  { code: "I", label: "I. מקלחות וחדרי רחצה" },
  { code: "J", label: "J. מטבחים ויחידות דיור" },
  { code: "K", label: "K. מאחזי יד" },
  { code: "L", label: "L. שילוט ותקשורת" },
  { code: "M", label: "M. אמצעי אזהרה לעיוורים" },
  { code: "N", label: "N. עמדות שירות ודלפקים" },
  { code: "O", label: "O. אולמות ומקומות ישיבה" },
];

export const PLACE_TYPE_LABELS: Record<string, string> = {
  exterior: "חצר/חוץ",
  interior: "פנים מבנה",
  restroom: "שירותים",
  parking: "חניה",
  "accessible-route": "דרך נגישה",
  apartment: "דיור",
  signage: "שילוט",
  vision: "ראייה",
  communication: "תקשורת",
};
